# generated by Neptune Namespaces v1.x.x
# file: Art/ColorExtractor/index.coffee

module.exports = require './namespace'
.includeInNamespace require './ColorExtractor'
.addModules
  ColorThief: require './ColorThief'
  Gradify:    require './Gradify'   
  Vibrant:    require './Vibrant'   