# generated by Neptune Namespaces v1.x.x
# file: Art/ColorExtractor/index.coffee

module.exports = require './namespace'
.addModules
  CanvasImage: require './CanvasImage'
  ColorThief:  require './ColorThief' 
  Fradify:     require './Fradify'    
  Index:       require './index'      
  Vibrant:     require './Vibrant'    
  Worker:      require './Worker'     