# generated by Neptune Namespaces v1.x.x
# file: Art/ColorExtractor/namespace.coffee

Art = require '../namespace'
module.exports = Art.ColorExtractor ||
Art.addNamespace 'ColorExtractor', class ColorExtractor extends Neptune.Base
  ;