# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Suite/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Suite'
.addModules
  Test10ArtStandardLib:         require './Test.10.ArtStandardLib'        
  Test11ArtClassSystem:         require './Test.11.ArtClassSystem'        
  Test11ArtFoundation:          require './Test.11.ArtFoundation'         
  Test12ArtCommunicationStatus: require './Test.12.ArtCommunicationStatus'
  Test13ArtConfig:              require './Test.13.ArtConfig'             
  Test14ArtObjectTreeFactory:   require './Test.14.ArtObjectTreeFactory'  
  Test15ArtRestClient:          require './Test.15.ArtRestClient'         
  Test20ArtAtomic:              require './Test.20.ArtAtomic'             
  Test30ArtCanvas:              require './Test.30.ArtCanvas'             
  Test31ArtText:                require './Test.31.ArtText'               
  Test32ArtEvents:              require './Test.32.ArtEvents'             
  Test32ArtXbd:                 require './Test.32.ArtXbd'                
  Test40ArtEngine:              require './Test.40.ArtEngine'             
  Test50ArtReact:               require './Test.50.ArtReact'              
  Test60ArtFlux:                require './Test.60.ArtFlux'               