// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Suite/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Suite',
  (class Suite extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
