# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Suite/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Suite', class Suite extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
