// generated by Neptune Namespaces v4.x.x
// file: Art.Text/index.js

(module.exports = require('./namespace'))

.addModules({
  Layout:             require('./Layout'),
  Metrics:            require('./Metrics'),
  TextLayoutFragment: require('./TextLayoutFragment')
});