# generated by Neptune Namespaces v3.x.x
# file: Art.Text/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Layout:             require './Layout'            
  Metrics:            require './Metrics'           
  TextLayoutFragment: require './TextLayoutFragment'