// generated by Neptune Namespaces v4.x.x
// file: Art.Text/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.Text',
  (class Text extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
