# generated by Neptune Namespaces v3.x.x
# file: Art.Text/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Text', class Text extends Neptune.PackageNamespace
  @version: require('../../package.json').version
