# generated by Neptune Namespaces
# file: tests/art/atomic/index.coffee

(module.exports = require './namespace')
.addModules
  Color:     require './color'
  Matrix:    require './matrix'
  Perimeter: require './perimeter'
  Point:     require './point'
  Rectangle: require './rectangle'
