# generated by Neptune Namespaces v2.x.x
# file: tests/art/atomic/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Color:     require './color'    
  Matrix:    require './matrix'   
  Perimeter: require './perimeter'
  Point:     require './point'    
  Rectangle: require './rectangle'