# generated by Neptune Namespaces
# file: test/tests/art/atomic/namespace.coffee

Art = require '../namespace'
module.exports = Art.Atomic ||
class Art.Atomic extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.Atomic"