# generated by Neptune Namespaces v1.x.x
# file: tests/art/atomic/namespace.coffee

Art = require '../namespace'
module.exports = Art.Atomic ||
Art.addNamespace 'Atomic', class Atomic extends Neptune.Base
  ;