// generated by Neptune Namespaces v4.x.x
// file: ArtAppKitBoilerPlate/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'ArtAppKitBoilerPlate',
  (class ArtAppKitBoilerPlate extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
