# generated by Neptune Namespaces v1.x.x
# file: Art/ColorExtractor/.Worker/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Worker'
.addModules
  CanvasImage: require './CanvasImage'
  Main:        require './Main'       