# generated by Neptune Namespaces v1.x.x
# file: Art/ColorExtractor/.Worker/namespace.coffee

ColorExtractor = require '../namespace'
module.exports = ColorExtractor.Worker ||
ColorExtractor.addNamespace 'Worker', class Worker extends Neptune.Base
  ;