// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Client'))
.addModules({
  AllFieldSubscriptionsMixin: require('./AllFieldSubscriptionsMixin'),
  Config:                     require('./Config'),
  Cordova:                    require('./Cordova'),
  Icons:                      require('./Icons'),
  Init:                       require('./init'),
  StandardImport:             require('./StandardImport'),
  ViewStateComponent:         require('./ViewStateComponent')
});
require('./ClientLib');
require('./Components');
require('./Models');