// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Client'))
.addModules({
  AllFieldSubscriptionsMixin: require('./AllFieldSubscriptionsMixin'),
  Init:                       require('./init'),
  StandardImport:             require('./StandardImport'),
  ViewStateComponent:         require('./ViewStateComponent')
});
require('./Components');
require('./InternalComponents');
require('./Models');