// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Client'))
.addModules({
  Init:           require('./init'),
  StandardImport: require('./StandardImport')
});
require('./Components');
require('./InternalComponents');
require('./Models');