// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/namespace.js

module.exports = require('../namespace').addNamespace(
  'Client',
  class Client extends Neptune.PackageNamespace {}
);
require('./Components/namespace');
require('./InternalComponents/namespace');
require('./Models/namespace');