# generated by Neptune Namespaces v3.x.x
# file: Art.CanvasPath/CanvasPathBuilder/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Builder:                   require './Builder'                  
  IntermediateCanvasPath:    require './IntermediateCanvasPath'   
  IntermediateCanvasPathSet: require './IntermediateCanvasPathSet'
  StandardImport:            require './StandardImport'           