// generated by Neptune Namespaces v4.x.x
// file: Art.CanvasPath/CanvasPathBuilder/index.js

(module.exports = require('./namespace'))

.addModules({
  Builder:                   require('./Builder'),
  IntermediateCanvasPath:    require('./IntermediateCanvasPath'),
  IntermediateCanvasPathSet: require('./IntermediateCanvasPathSet'),
  StandardImport:            require('./StandardImport')
});