// generated by Neptune Namespaces v4.x.x
// file: Art.CanvasPath/CanvasPathBuilder/namespace.js

module.exports = require('../namespace').addNamespace(
  'CanvasPathBuilder',
  class CanvasPathBuilder extends Neptune.PackageNamespace {}
);
