# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/CanvasPathFile/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './CanvasPathFile'
.addModules
  CanvasPath:        require './CanvasPath'       
  CanvasPathLibrary: require './CanvasPathLibrary'
  CanvasPathSet:     require './CanvasPathSet'    
  StandardImport:    require './StandardImport'   