# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/CanvasPathFile/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  EncodedNamedPathSet: require './EncodedNamedPathSet'
  EncodedPath:         require './EncodedPath'        
  EncodedPathSet:      require './EncodedPathSet'     
  StandardImport:      require './StandardImport'     