// generated by Neptune Namespaces v4.x.x
// file: Art.FrameStats/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./FrameStats'))
.addModules({
  FrameSampleSet:   require('./FrameSampleSet'),
  FrameStatStorage: require('./FrameStatStorage'),
  Main:             require('./Main'),
  StandardImport:   require('./StandardImport'),
  Style:            require('./Style')
});