// generated by Neptune Namespaces v4.x.x
// file: Art.FrameStats/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.FrameStats',
  (class FrameStats extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
