# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/Encoding/namespace.coffee

module.exports = (require '../namespace').addNamespace('Encoding', class Encoding extends Neptune.PackageNamespace)
