# generated by Neptune Namespaces v3.x.x
# file: Imikimi.AppKit/_Client/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  AppKitViewState: require './AppKitViewState'