# generated by Neptune Namespaces v3.x.x
# file: Imikimi.AppKit/_Client/Models/namespace.coffee

module.exports = (require '../namespace').addNamespace('Models', class Models extends Neptune.PackageNamespace)
