# generated by Neptune Namespaces v3.x.x
# file: Imikimi.AppKit/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Imikimi.AppKit', class AppKit extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Style/namespace'