# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './SvgPathExtractor'
.addModules
  StandardImport: require './StandardImport'
require './Encoded'
require './Encoding'
require './Extractor'