# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './SvgPathExtractor'
.addModules
  CanvgCanvasMock: require './CanvgCanvasMock'
  EncodedPath:     require './EncodedPath'    
  EncodedPathSet:  require './EncodedPathSet' 
  EncodingLib:     require './EncodingLib'    
  StandardImport:  require './StandardImport' 
  SvgPath:         require './SvgPath'        
  SvgPathSet:      require './SvgPathSet'     
  XbdFactories:    require './XbdFactories'   