# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './SvgPathExtractor'
.addModules
  CanvgCanvasMock: require './CanvgCanvasMock'
  StandardImport:  require './StandardImport' 
  SvgPath:         require './SvgPath'        