# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.SvgPathExtractor', class SvgPathExtractor extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './CanvasPathBuilder/namespace';
require './CanvasPathFile/namespace';
require './Encoding/namespace';
require './Extractor/namespace'