// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Pusher/index.js

(module.exports = require('./namespace'))

.addModules({
  PusherFilter:         require('./PusherFilter'),
  PusherFluxModelMixin: require('./PusherFluxModelMixin')
});
require('./Pipelines');