// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Pusher/index.js

(module.exports = require('./namespace'))

.addModules({
  PusherArtModelMixin: require('./PusherArtModelMixin'),
  PusherFilter:        require('./PusherFilter'),
  PusherServiceCalls:  require('./PusherServiceCalls')
});
require('./Pipelines');