// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Pusher/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.EryExtensions.Pusher',
  (class Pusher extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Pipelines/namespace');