// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  Button:          require('./Button'),
  Icon:            require('./Icon'),
  IconButton:      require('./IconButton'),
  ScrollerWithBar: require('./ScrollerWithBar'),
  StandardImport:  require('./StandardImport'),
  Toggle:          require('./Toggle')
});