// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/Widgets/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Widgets'))
.addModules({
  ActivityBadge:       require('./ActivityBadge'),
  Button:              require('./Button'),
  Icon:                require('./Icon'),
  IconButton:          require('./IconButton'),
  ScrollerWithBar:     require('./ScrollerWithBar'),
  SelectedTextPopover: require('./SelectedTextPopover'),
  StandardImport:      require('./StandardImport'),
  TabbedSection:       require('./TabbedSection'),
  TabbedSectionTabs:   require('./TabbedSectionTabs'),
  Toggle:              require('./Toggle'),
  ToolbarButton:       require('./ToolbarButton'),
  WidgetLib:           require('./WidgetLib')
});