# generated by Neptune Namespaces v0.5
# file: tests/art/aws/StreamlinedApi/index.coffee

module.exports = require './namespace'
.addModules
  StreamlinedDynamoDbApi: require './StreamlinedDynamoDbApi'