# generated by Neptune Namespaces v0.5
# file: tests/art/aws/StreamlinedApi/namespace.coffee

Aws = require '../namespace'
module.exports = Aws.StreamlinedApi ||
Aws.addNamespace 'StreamlinedApi', class StreamlinedApi extends Neptune.Base
  ;