// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteDemos/Demos/DrawAnimations/namespace.js

module.exports = require('../namespace').addNamespace(
  'DrawAnimations',
  class DrawAnimations extends Neptune.PackageNamespace {}
);
