// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/KitchenSink/namespace.js

module.exports = require('../namespace').addNamespace(
  'KitchenSink',
  class KitchenSink extends Neptune.PackageNamespace {}
);
require('./Components/namespace');