# generated by Neptune Namespaces v0.1.0
# file: art/webgl/index.coffee

(module.exports = require './namespace')
.addModules
  Bitmap:                 require './bitmap'
  ContextManager:         require './context_manager'
  Detector:               require './detector'
  OffscreenRenderTarget:  require './offscreen_render_target'
  Shader:                 require './shader'
  ShaderProgram:          require './shader_program'
  ShaderPrograms:         require './shader_programs'
  ShaderRenderer:         require './shader_renderer'
  ShaderRendererColored:  require './shader_renderer_colored'
  ShaderRendererTextured: require './shader_renderer_textured'