# generated by Neptune Namespaces
# file: src/art/webgl/namespace.coffee

Art = require '../namespace'
module.exports = Art.Webgl ||
class Art.Webgl extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Webgl"

Art.addNamespace Art.Webgl