# generated by Neptune Namespaces
# this file: test/tests/flux/react/index.coffee

module.exports =
React                   = require './namespace'
React.FluxComponent     = require './flux_component'
React.FluxComponentBase = require './flux_component_base'
React.finishLoad(
  ["FluxComponent","FluxComponentBase"]
)