# generated by Neptune Namespaces
# file: test/tests/flux/react/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.React ||
class Flux.React extends Neptune.Base
  @namespace: Flux
  @namespacePath: "Neptune.Tests.Flux.React"

Flux.addNamespace Flux.React