// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ExpressServer/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.ExpressServer',
  class ExpressServer extends Neptune.PackageNamespace {}
);
