# generated by Neptune Namespaces
# file: art/react/index.coffee

(module.exports = require './namespace')
.addModules
  All:                 require './all'
  Component:           require './component'
  HotStyleProps:       require './hot_style_props'
  ReactArtEngineEpoch: require './react_art_engine_epoch'
  VirtualElement:      require './virtual_element'
  VirtualNode:         require './virtual_node'
