# generated by Neptune Namespaces v0.3.0
# file: art/react_specializations/index.coffee

(module.exports = require './namespace')
.addModules
  Aim:                 require './aim'
  ArtEngine:           require './art_engine'
  ArtEngineRemote:     require './art_engine_remote'
  Dom:                 require './dom'
  PagingScrollElement: require './paging_scroll_element'