# generated by Neptune Namespaces
# file: art/react_specializations/namespace.coffee

Art = require '../namespace'
module.exports = Art.ReactSpecializations ||
class Art.ReactSpecializations extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.ReactSpecializations"

Art.addNamespace Art.ReactSpecializations