# generated by Neptune Namespaces
# file: art/react_specializations/namespace.coffee

Art = require '../namespace'
module.exports = Art.ReactSpecializations ||
Art.addNamespace class ReactSpecializations extends Neptune.Base
  ;