// generated by Neptune Namespaces v4.x.x
// file: tests/Art/Flux/Core/index.js

(module.exports = require('./namespace'))

.addModules({
  FluxModel:              require('./FluxModel'),
  FluxStore:              require('./FluxStore'),
  FluxSubscriptionsMixin: require('./FluxSubscriptionsMixin')
});