# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.DynamoDb/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.EryExtensions.DynamoDb', class DynamoDb extends Neptune.PackageNamespace
  @version: require('../../package.json').version
