# generated by Neptune Namespaces v3.x.x
# file: tests/Art.React/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ComponentLifecycle: require './component_lifecycle'
  Component:          require './Component'          
  Main:               require './Main'               
  VirtualElement:     require './VirtualElement'     