// generated by Neptune Namespaces v4.x.x
// file: tests/Art.React/index.js

(module.exports = require('./namespace'))

.addModules({
  ComponentLifecycle: require('./component_lifecycle'),
  Component:          require('./Component'),
  Main:               require('./Main'),
  VirtualElement:     require('./VirtualElement')
});