// generated by Neptune Namespaces v4.x.x
// file: tests/Art.React/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.React',
  (class React extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
