# generated by Neptune Namespaces v3.x.x
# file: tests/Art.React/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.React', class React extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
