// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/KitchenSinkDemo/Components/Pages/index.js

(module.exports = require('./namespace'))

.addModules({
  Home:    require('./Home'),
  Widgets: require('./Widgets')
});