// generated by Neptune Namespaces v4.x.x
// file: perfs/Art/Atomic/namespace.js

module.exports = require('../namespace').addNamespace(
  'Atomic',
  class Atomic extends Neptune.PackageNamespace {}
);
