# generated by Neptune Namespaces
# file: art-text/src/art/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Art ||
class Neptune.Art extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Art"

Neptune.addNamespace Neptune.Art
