// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Components.Dom/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Components.Dom',
  (class Dom extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
