// generated by Neptune Namespaces v4.x.x
// file: Art.Chat/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.Chat',
  (class Chat extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Client/namespace');
require('./Configurations/namespace');
require('./Pipelines/namespace');