// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/Lib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Lib'))
.addModules({
  TimeConstants: require('./TimeConstants')
});