# generated by Neptune Namespaces v0.1.0
# file: tests/art/flux/react/index.coffee

(module.exports = require './namespace')
.addModules
  FluxComponent:     require './flux_component'
  FluxComponentBase: require './flux_component_base'