# generated by Neptune Namespaces v1.x.x
# file: tests/art/flux/react/index.coffee

module.exports = require './namespace'
.addModules
  FluxComponentBase: require './flux_component_base'
  FluxComponent:     require './flux_component'     