# generated by Neptune Namespaces v1.x.x
# file: tests/art/flux/react/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.React ||
Flux.addNamespace 'React', class React extends Neptune.Base
  ;