# generated by Neptune Namespaces v0.3.0
# file: tests/art/flux/react/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.React ||
Flux.addNamespace 'React', class React extends Neptune.Base
  ;