# generated by Neptune Namespaces v3.x.x
# file: Tests.Art.Ery.IndexedDb/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Tests.Art.Ery.IndexedDb', class IndexedDb extends Neptune.PackageNamespace
  @version: require('../../package.json').version
