// generated by Neptune Namespaces v4.x.x
// file: Tests.Art.Ery.IndexedDb/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Tests.Art.Ery.IndexedDb',
  (class IndexedDb extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
