# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/CanvasPathBuilder/namespace.coffee

module.exports = (require '../namespace').addNamespace('CanvasPathBuilder', class CanvasPathBuilder extends Neptune.PackageNamespace)
