// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Pusher/Pipelines/index.js

(module.exports = require('./namespace'))

.addModules({
  SimpleStore: require('./SimpleStore')
});