# generated by Neptune Namespaces
# file: art/suite/namespace.coffee

Art = require '../namespace'
module.exports = Art.Suite ||
class Art.Suite extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Suite"

Art.addNamespace Art.Suite