# generated by Neptune Namespaces v3.x.x
# file: tests2/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Tests2', class Tests2 extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Art/namespace'