// generated by Neptune Namespaces v4.x.x
// file: Art.Components.Dom/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Dom'))
.addModules({
  DomVirtualElement: require('./DomVirtualElement'),
  StandardImport:    require('./StandardImport')
});