// generated by Neptune Namespaces v4.x.x
// file: Art.Components.Dom/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Components.Dom',
  (class Dom extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
