# generated by Neptune Namespaces v0.6
# file: tests/art/aws/StreamlinedDynamoDbApi/index.coffee

module.exports = require './namespace'
.addModules
  CreateTable:       require './CreateTable'      
  PutItem:           require './PutItem'          
  Query:             require './Query'            
  TableApiBaseClass: require './TableApiBaseClass'