# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Aws/StreamlinedDynamoDbApi/index.coffee

module.exports = require './namespace'
.addModules
  CreateTable:       require './CreateTable'      
  PutItem:           require './PutItem'          
  Query:             require './Query'            
  TableApiBaseClass: require './TableApiBaseClass'