// generated by Neptune Namespaces v4.x.x
// file: tests/art/aws/StreamlinedDynamoDbApi/index.js

(module.exports = require('./namespace'))

.addModules({
  CreateTable:       require('./CreateTable'),
  DeleteItem:        require('./DeleteItem'),
  PutItem:           require('./PutItem'),
  Query:             require('./Query'),
  TableApiBaseClass: require('./TableApiBaseClass'),
  UpdateItem:        require('./UpdateItem')
});