# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Aws/StreamlinedDynamoDbApi/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CreateTable:       require './CreateTable'      
  DeleteItem:        require './DeleteItem'       
  PutItem:           require './PutItem'          
  Query:             require './Query'            
  TableApiBaseClass: require './TableApiBaseClass'
  UpdateItem:        require './UpdateItem'       