# generated by Neptune Namespaces v0.5
# file: tests/art/aws/StreamlinedDynamoDbApi/namespace.coffee

Aws = require '../namespace'
module.exports = Aws.StreamlinedDynamoDbApi ||
Aws.addNamespace 'StreamlinedDynamoDbApi', class StreamlinedDynamoDbApi extends Neptune.Base
  ;