// generated by Neptune Namespaces v4.x.x
// file: tests/Art/Aws/StreamlinedDynamoDbApi/namespace.js

module.exports = require('../namespace').addNamespace(
  'StreamlinedDynamoDbApi',
  class StreamlinedDynamoDbApi extends Neptune.PackageNamespace {}
);
