// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuthDemos/Basic/_Client/index.js

(module.exports = require('./namespace'))

.addModules({
  Home:           require('./Home'),
  Main:           require('./Main'),
  StandardImport: require('./StandardImport')
});