// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuthDemos/Basic/_Client/namespace.js

module.exports = require('../namespace').addNamespace(
  'Client',
  (class Client extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../package.json'))
);
