// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Core/Pipeline/index.js

(module.exports = require('./namespace'))

.addModules({
  PipelineAliases:        require('./PipelineAliases'),
  PipelineBasics:         require('./PipelineBasics'),
  PipelineCustomRequests: require('./PipelineCustomRequests'),
  PipelineFailures:       require('./PipelineFailures'),
  PipelineHandlers:       require('./PipelineHandlers'),
  PipelineSubrequests:    require('./PipelineSubrequests')
});