# generated by Neptune Namespaces
# file: art/text/index.coffee

(module.exports = require './namespace')
.addModules
  Layout:             require './layout'
  Metrics:            require './metrics'
  TextLayoutFragment: require './text_layout_fragment'
