# generated by Neptune Namespaces
# this file: art-text/src/art/text/index.coffee

module.exports =
Text                    = require './namespace'
Text.Layout             = require './layout'
Text.Metrics            = require './metrics'
Text.TextLayoutFragment = require './text_layout_fragment'
Text.finishLoad(
  ["Layout","Metrics","TextLayoutFragment"]
)
