# generated by Neptune Namespaces v0.5
# file: art/text/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_text'
.addModules
  Layout:             require './layout'              
  Metrics:            require './metrics'             
  TextLayoutFragment: require './text_layout_fragment'