# generated by Neptune Namespaces
# file: art-text/src/art/text/namespace.coffee

Art = require '../namespace'
module.exports = Art.Text ||
class Art.Text extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Text"

Art.addNamespace Art.Text
