# generated by Neptune Namespaces
# file: test/tests/art/flux/namespace.coffee

Art = require '../namespace'
module.exports = Art.Flux ||
class Art.Flux extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.Flux"

Art.addNamespace Art.Flux