# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Flux/namespace.coffee

Art = require '../namespace'
module.exports = Art.Flux ||
Art.addNamespace 'Flux', class Flux extends Neptune.Base
  ;