# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Flux/namespace.coffee

Art = require '../namespace'
module.exports = Art.Flux ||
Art.addNamespace 'Flux', class Flux extends Neptune.Base
  ;
require './Core/namespace';
require './React/namespace'