# generated by Neptune Namespaces v0.3.0
# file: tests/art/flux/namespace.coffee

Art = require '../namespace'
module.exports = Art.Flux ||
Art.addNamespace 'Flux', class Flux extends Neptune.Base
  ;