// generated by Neptune Namespaces v4.x.x
// file: Art.EryExtensions.Elasticsearch/Pipelines/Caf-WIP/namespace.js

module.exports = require('../namespace').addNamespace(
  'CafWip',
  class CafWip extends Neptune.PackageNamespace {}
);
