# generated by Neptune Namespaces v0.5
# file: art/flux/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_flux'
require './core'
require './db'
require './models'
require './react'