# generated by Neptune Namespaces
# file: art/flux/index.coffee

(module.exports = require './namespace')
.addModules
  All:    require './all'
require './core'
require './db'
require './models'
require './react'