# generated by Neptune Namespaces
# file: src/art/flux/namespace.coffee

Art = require '../namespace'
module.exports = Art.Flux ||
class Art.Flux extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Flux"

Art.addNamespace Art.Flux