// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServer/index.js

(module.exports = require('./namespace'))

.addModules({
  AuthRequests:           require('./AuthRequests'),
  ClientFailures:         require('./ClientFailures'),
  CompoundKeys:           require('./CompoundKeys'),
  FilterLocationRequests: require('./FilterLocationRequests'),
  MyRemoteRequests:       require('./MyRemoteRequests'),
  Sessions:               require('./Sessions'),
  StandardImport:         require('./StandardImport'),
  StaticAssets:           require('./StaticAssets')
});
require('./Pipelines');