# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/App/namespace.coffee

Suite = require '../namespace'
module.exports = Suite.App ||
Suite.addNamespace 'App', class App extends Neptune.Base
  ;
require './Tools/namespace'