# generated by Neptune Namespaces v2.x.x
# file: Art/ExpressServer/namespace.coffee

Art = require '../namespace'
module.exports = Art.ExpressServer ||
Art.addNamespace 'ExpressServer', class ExpressServer extends Neptune.Base
  ;
