# generated by Neptune Namespaces v3.x.x
# file: Art/Atomic/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Atomic'
.addModules
  Base:      require './Base'     
  Color:     require './Color'    
  Matrix:    require './Matrix'   
  Perimeter: require './Perimeter'
  Point:     require './Point'    
  Rectangle: require './Rectangle'