# generated by Neptune Namespaces v3.x.x
# file: Art/Atomic/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Atomic', class Atomic extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
