# generated by Neptune Namespaces v3.x.x
# file: Art/Aws/StreamlinedDynamoDbApi/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './StreamlinedDynamoDbApi'
.addModules
  BatchGetItem:      require './BatchGetItem'     
  Common:            require './Common'           
  CreateTable:       require './CreateTable'      
  DeleteItem:        require './DeleteItem'       
  GetItem:           require './GetItem'          
  PutItem:           require './PutItem'          
  Query:             require './Query'            
  Scan:              require './Scan'             
  TableApiBaseClass: require './TableApiBaseClass'
  UpdateItem:        require './UpdateItem'       