# generated by Neptune Namespaces v2.x.x
# file: Art/Aws/StreamlinedDynamoDbApi/namespace.coffee

Aws = require '../namespace'
module.exports = Aws.StreamlinedDynamoDbApi ||
Aws.addNamespace 'StreamlinedDynamoDbApi', class StreamlinedDynamoDbApi extends Neptune.Base
  ;
