# generated by Neptune Namespaces v3.x.x
# file: Art/Aws/StreamlinedDynamoDbApi/namespace.coffee

module.exports = (require '../namespace').addNamespace('StreamlinedDynamoDbApi', class StreamlinedDynamoDbApi extends Neptune.PackageNamespace)
