// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Epoch.Stats/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Epoch.Stats',
  (class Stats extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
