// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Flux/index.js

(module.exports = require('./namespace'))

.addModules({
  ApplicationStateTest: require('./ApplicationState.test'),
  FluxModelTest:        require('./FluxModel.test')
});
require('./React');