// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Flux/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Art.Flux');
require('./React/namespace');