// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Flux/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Flux',
  class Flux extends Neptune.PackageNamespace {}
);
require('./React/namespace');