# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/App/Node/namespace.coffee

App = require '../namespace'
module.exports = App.Node ||
App.addNamespace 'Node', class Node extends Neptune.Base
  ;