// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuth/Pipelines/index.js

(module.exports = require('./namespace'))

.addModules({
  AuthenticationKey: require('./AuthenticationKey'),
  Password:          require('./Password'),
  Session:           require('./Session'),
  StandardImport:    require('./StandardImport')
});