// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuth/Pipelines/namespace.js

module.exports = require('../namespace').addNamespace(
  'Pipelines',
  class Pipelines extends Neptune.PackageNamespace {}
);
