# generated by Neptune Namespaces v0.5
# file: art/engine/demos/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Demos ||
Engine.addNamespace 'Demos', class Demos extends Neptune.Base
  ;