# generated by Neptune Namespaces v1.x.x
# file: tests/art/ery/aws/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Aws ||
Ery.addNamespace 'Aws', class Aws extends Neptune.Base
  ;