# generated by Neptune Namespaces v0.4.1
# file: tests/art/ery/aws/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Aws ||
Ery.addNamespace 'Aws', class Aws extends Neptune.Base
  ;