# generated by Neptune Namespaces
# this file: src/art/engine/demos/paging_scroll_element/index.coffee

module.exports =
PagingScrollElement      = require './namespace'
PagingScrollElement.Main = require './main'
PagingScrollElement.finishLoad(
  ["Main"]
)