# generated by Neptune Namespaces v1.x.x
# file: art/engine/demos/paging_scroll_element/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.PagingScrollElement ||
Demos.addNamespace 'PagingScrollElement', class PagingScrollElement extends Neptune.Base
  ;