# generated by Neptune Namespaces v3.x.x
# file: art/engine/demos/paging_scroll_element/namespace.coffee

module.exports = (require '../namespace').addNamespace('PagingScrollElement', class PagingScrollElement extends Neptune.PackageNamespace)
