# generated by Neptune Namespaces v3.x.x
# file: Art.AppKitDemo/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main:           require './Main'          
  StandardImport: require './StandardImport'
require './Components'