# generated by Neptune Namespaces v3.x.x
# file: Art.AppKitDemo/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.AppKitDemo', class AppKitDemo extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Components/namespace'