# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery.Indexed.Db/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Ery.Indexed.Db', class Db extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
