# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Aws/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  SqsPipeline: require './SqsPipeline'
require './DynamoDbPipeline'