// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Aws/index.js

(module.exports = require('./namespace'))

.addModules({
  SqsPipeline: require('./SqsPipeline')
});
require('./DynamoDbPipeline');