# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Aws/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.EryExtensions.Aws', class Aws extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './DynamoDbPipeline/namespace'