// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Aws/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.EryExtensions.Aws',
  (class Aws extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./DynamoDbPipeline/namespace');