// generated by Neptune Namespaces v4.x.x
// file: tests/Art.App.Kit/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.App.Kit',
  (class Kit extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
