# generated by Neptune Namespaces v3.x.x
# file: tests/Art.App.Kit/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.App.Kit', class Kit extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
