# generated by Neptune Namespaces v2.x.x
# file: Art/Flux/.React/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './React'
.addModules
  FluxComponent: require './FluxComponent'