# generated by Neptune Namespaces v2.x.x
# file: Art/Flux/.React/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.React ||
Flux.addNamespace 'React', class React extends Neptune.Base
  ;
