# generated by Neptune Namespaces v2.x.x
# file: Art/Flux/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Flux'
require './Core'
require './Models'
require './React'