# generated by Neptune Namespaces v3.x.x
# file: Art/Flux/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Flux', class Flux extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './Core/namespace';
require './Models/namespace'