# generated by Neptune Namespaces
# this file: src/art/engine/demos/basic/index.coffee

module.exports =
Basic      = require './namespace'
Basic.Main = require './main'
Basic.finishLoad(
  ["Main"]
)