# generated by Neptune Namespaces v3.x.x
# file: art/engine/demos/basic/namespace.coffee

module.exports = (require '../namespace').addNamespace('Basic', class Basic extends Neptune.PackageNamespace)
