// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/InternalComponents/index.js

(module.exports = require('./namespace'))

.addModules({
  MainPageStacks: require('./MainPageStacks'),
  PageStack:      require('./PageStack')
});