// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/ClientLib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./ClientLib'))
.addModules({
  Assets: require('./Assets')
});