// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/ClientLib/namespace.js

module.exports = require('../namespace').addNamespace(
  'ClientLib',
  class ClientLib extends Neptune.PackageNamespace {}
);
