// generated by Neptune Namespaces v4.x.x
// file: tests/Art.CanvasPath/index.js

(module.exports = require('./namespace'))

.addModules({
  ConvertAllExamples: require('./ConvertAllExamples'),
  ConvertOutputTests: require('./ConvertOutputTests'),
  Data:               require('./Data')
});