// generated by Neptune Namespaces v4.x.x
// file: tests/Art.CanvasPath/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.CanvasPath',
  (class CanvasPath extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
