# generated by Neptune Namespaces v3.x.x
# file: tests/Art.CanvasPath/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.CanvasPath', class CanvasPath extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
