# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.Aws/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DynamoDbPipeline: require './DynamoDbPipeline'
  SqsPipeline:      require './SqsPipeline'     