// generated by Neptune Namespaces v4.x.x
// file: Art.EryExtensions.Aws/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.EryExtensions.Aws',
  (class Aws extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
