# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.Aws/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.EryExtensions.Aws', class Aws extends Neptune.PackageNamespace
  @version: require('../../package.json').version
