# generated by Neptune Namespaces v0.5
# file: art/aws/StreamlinedApi/index.coffee

module.exports = require './namespace'
.addModules
  StreamlinedDynamoDbApi: require './StreamlinedDynamoDbApi'
  Tools:                  require './Tools'                 