# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Aws/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Aws4RestClient: require './Aws4RestClient'
  DynamoDb:       require './DynamoDb'      
require './StreamlinedDynamoDbApi'