// generated by Neptune Namespaces v4.x.x
// file: tests/Art/Aws/index.js

(module.exports = require('./namespace'))

.addModules({
  Aws4RestClient: require('./Aws4RestClient'),
  DynamoDb:       require('./DynamoDb'),
  S3:             require('./S3'),
  Sqs:            require('./Sqs')
});
require('./StreamlinedDynamoDbApi');