# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Aws/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Aws4RestClient: require './Aws4RestClient'
  DynamoDb:       require './DynamoDb'      
  S3:             require './S3'            
  Sqs:            require './Sqs'           
require './StreamlinedDynamoDbApi'