# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Aws/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DynamoDb: require './DynamoDb'
require './StreamlinedDynamoDbApi'