// generated by Neptune Namespaces v4.x.x
// file: tests/art/aws/namespace.js

module.exports = require('../namespace').addNamespace(
  'Aws',
  (class Aws extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../package.json'))
);
require('./StreamlinedDynamoDbApi/namespace');