// generated by Neptune Namespaces v4.x.x
// file: tests/Art/Aws/namespace.js

module.exports = require('../namespace').addNamespace(
  'Aws',
  class Aws extends Neptune.PackageNamespace {}
);
require('./StreamlinedDynamoDbApi/namespace');