# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Aws/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Aws', class Aws extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
require './StreamlinedDynamoDbApi/namespace'