# generated by Neptune Namespaces v3.x.x
# file: Art.EngineDemos/PagingScrollElement/namespace.coffee

module.exports = (require '../namespace').addNamespace('PagingScrollElement', class PagingScrollElement extends Neptune.PackageNamespace)
