# generated by Neptune Namespaces
# this file: src/art/flux/models/index.coffee

module.exports =
Models                    = require './namespace'
Models.ApplicationState   = require './application_state'
Models.VolatileModel      = require './volatile_model'
Models.VolatileQueryModel = require './volatile_query_model'
Models.VolatileStore      = require './volatile_store'
Models.finishLoad(
  ["ApplicationState","VolatileModel","VolatileQueryModel","VolatileStore"]
)