# generated by Neptune Namespaces v1.x.x
# file: art/flux/models/index.coffee

module.exports = require './namespace'
.addModules
  ApplicationState:   require './application_state'   
  VolatileModel:      require './volatile_model'      
  VolatileQueryModel: require './volatile_query_model'
  VolatileStore:      require './volatile_store'      