# generated by Neptune Namespaces v0.5
# file: art/flux/models/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Models ||
Flux.addNamespace 'Models', class Models extends Neptune.Base
  ;