# generated by Neptune Namespaces
# file: src/art/flux/models/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Models ||
class Flux.Models extends Neptune.Base
  @namespace: Flux
  @namespacePath: "Neptune.Art.Flux.Models"

Flux.addNamespace Flux.Models