# generated by Neptune Namespaces v0.1.0
# file: art/flux/models/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Models ||
Flux.addNamespace class Models extends Neptune.Base
  ;