# generated by Neptune Namespaces v2.x.x
# file: Art/Suite/App/Tools/namespace.coffee

App = require '../namespace'
module.exports = App.Tools ||
App.addNamespace 'Tools', class Tools extends Neptune.Base
  ;
