# generated by Neptune Namespaces v0.5
# file: tests/art/engine.remote/index.coffee

module.exports = require './namespace'
.addModules
  Receiver: require './receiver'
  Remote:   require './remote'  