# generated by Neptune Namespaces v1.x.x
# file: tests/art/engine.remote/namespace.coffee

Art = require '../namespace'
module.exports = Art.EngineRemote ||
Art.addNamespace 'EngineRemote', class EngineRemote extends Neptune.Base
  ;