# generated by Neptune Namespaces
# file: tests/art/engine.remote/namespace.coffee

Art = require '../namespace'
module.exports = Art.EngineRemote ||
class Art.EngineRemote extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.EngineRemote"

Art.addNamespace Art.EngineRemote