# generated by Neptune Namespaces
# file: tests/art/engine.remote/namespace.coffee

Art = require '../namespace'
module.exports = Art.EngineRemote ||
Art.addNamespace class EngineRemote extends Neptune.Base
  ;