# generated by Neptune Namespaces
# this file: src/art/engine/demos/clipping/index.coffee

module.exports =
Clipping      = require './namespace'
Clipping.Main = require './main'
Clipping.finishLoad(
  ["Main"]
)