# generated by Neptune Namespaces v1.x.x
# file: art/engine/demos/clipping/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Clipping ||
Demos.addNamespace 'Clipping', class Clipping extends Neptune.Base
  ;