# generated by Neptune Namespaces
# file: src/art/engine/demos/clipping/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Clipping ||
class Demos.Clipping extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.Engine.Demos.Clipping"

Demos.addNamespace Demos.Clipping