# generated by Neptune Namespaces v1.x.x
# file: Art/Flux/.DepricatedModels/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.DepricatedModels ||
Flux.addNamespace 'DepricatedModels', class DepricatedModels extends Neptune.Base
  ;