// generated by Neptune Namespaces v4.x.x
// file: SimpleClientServer/_Client/index.js

(module.exports = require('./namespace'))

.addModules({
  App:                  require('./App'),
  Main:                 require('./Main'),
  SimplePipelineResult: require('./SimplePipelineResult'),
  Style:                require('./Style')
});