// generated by Neptune Namespaces v4.x.x
// file: SimpleClientServer/_Client/index.js

(module.exports = require('./namespace'))

.addModules({
  App:            require('./App'),
  Main:           require('./Main'),
  StandardImport: require('./StandardImport')
});