# generated by Neptune Namespaces
# file: test/tests/flux/models/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Models ||
class Flux.Models extends Neptune.Base
  @namespace: Flux
  @namespacePath: "Neptune.Tests.Flux.Models"

Flux.addNamespace Flux.Models