# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Flux/Models/index.coffee

module.exports = require './namespace'
.addModules
  TestVolatileModel:  require './TestVolatileModel' 
  TestVolatileStore:  require './TestVolatileStore' 
  VolatileModel:      require './VolatileModel'     
  VolatileQueryModel: require './VolatileQueryModel'
  VolatileStore:      require './VolatileStore'     