// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteServer/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.SuiteServer',
  (class SuiteServer extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Handlers/namespace');