// generated by Neptune Namespaces v4.x.x
// file: Ace.Demo/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:           require('./Main'),
  RootComponent:  require('./RootComponent'),
  StandardImport: require('./StandardImport')
});