// generated by Neptune Namespaces v4.x.x
// file: Ace.Demo/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Ace.Demo',
  (class Demo extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
