# generated by Neptune Namespaces v3.x.x
# file: Art.CanvasPath/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './CanvasPath'
.addModules
  StandardImport: require './StandardImport'
require './CanvasPathBuilder'
require './CanvasPathFile'
require './Encoding'
require './Extractor'