// generated by Neptune Namespaces v4.x.x
// file: Art.CanvasPath/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./CanvasPath'))
.addModules({
  StandardImport: require('./StandardImport')
});
require('./CanvasPathBuilder');
require('./CanvasPathFile');
require('./Encoding');
require('./Extractor');