// generated by Neptune Namespaces v4.x.x
// file: Art.CanvasPath/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.CanvasPath',
  (class CanvasPath extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./CanvasPathBuilder/namespace');
require('./CanvasPathFile/namespace');
require('./Encoding/namespace');
require('./Extractor/namespace');