// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Text/index.js

(module.exports = require('./namespace'))

.addModules({
  Draw:    require('./Draw'),
  Fonts:   require('./Fonts'),
  Layout:  require('./Layout'),
  Layout2: require('./Layout2'),
  Metrics: require('./Metrics')
});