# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Text/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Draw:    require './Draw'   
  Fonts:   require './Fonts'  
  Layout:  require './Layout' 
  Layout2: require './Layout2'
  Metrics: require './Metrics'