// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Text/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Text',
  (class Text extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
