# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Text/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Text', class Text extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
