# generated by Neptune Namespaces v2.x.x
# file: Art/Flux/Models/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Models ||
Flux.addNamespace 'Models', class Models extends Neptune.Base
  ;
