// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.AppKitDemos',
  (class AppKitDemos extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./KitchenSink/namespace');
require('./Minimum/namespace');
require('./NativePreview/namespace');