// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuth/_Client/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Client'))
.addModules({
  StandardImport: require('./StandardImport')
});
require('./Components');