# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/Encoded/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  EncodedPath:    require './EncodedPath'   
  EncodedPathSet: require './EncodedPathSet'
  StandardImport: require './StandardImport'