# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/Encoded/namespace.coffee

module.exports = (require '../namespace').addNamespace('Encoded', class Encoded extends Neptune.PackageNamespace)
