// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/ArtEryFlux/index.js

(module.exports = require('./namespace'))

.addModules({
  ArtEryFluxModel:      require('./ArtEryFluxModel'),
  ArtEryQueryFluxModel: require('./ArtEryQueryFluxModel'),
  StandardImport:       require('./StandardImport')
});