// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/ArtEryFlux/namespace.js

module.exports = require('../namespace').addNamespace(
  'ArtEryFlux',
  class ArtEryFlux extends Neptune.PackageNamespace {}
);
