# generated by Neptune Namespaces
# file: tests/art/react/index.coffee

(module.exports = require './namespace')
.addModules
  Component:          require './component'
  ComponentLifecycle: require './component_lifecycle'
  Main:               require './main'
  VirtualElement:     require './virtual_element'
