# generated by Neptune Namespaces v1.x.x
# file: tests/art/react/index.coffee

module.exports = require './namespace'
.addModules
  ComponentLifecycle: require './component_lifecycle'
  Component:          require './component'          
  Main:               require './main'               
  VirtualElement:     require './virtual_element'    