# generated by Neptune Namespaces
# file: test/tests/art/react/namespace.coffee

Art = require '../namespace'
module.exports = Art.React ||
class Art.React extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.React"

Art.addNamespace Art.React