# generated by Neptune Namespaces v3.x.x
# file: tests/art/react/namespace.coffee

module.exports = (require '../namespace').addNamespace 'React', class React extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
