# generated by Neptune Namespaces v0.5
# file: tests/art/react/namespace.coffee

Art = require '../namespace'
module.exports = Art.React ||
Art.addNamespace 'React', class React extends Neptune.Base
  ;