// generated by Neptune Namespaces v4.x.x
// file: Art.Markdown/_Client/index.js

(module.exports = require('./namespace'))

.addModules({
  CodePalette:    require('./CodePalette'),
  MarkdownView:   require('./MarkdownView'),
  MenuMarkdown:   require('./MenuMarkdown'),
  StandardImport: require('./StandardImport')
});