# generated by Neptune Namespaces v0.5
# file: art/engine/demos/form/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Form ||
Demos.addNamespace 'Form', class Form extends Neptune.Base
  ;