# generated by Neptune Namespaces
# file: src/art/engine/demos/form/namespace.coffee

Demos = require '../namespace'
module.exports = Demos.Form ||
class Demos.Form extends Neptune.Base
  @namespace: Demos
  @namespacePath: "Neptune.Art.Engine.Demos.Form"

Demos.addNamespace Demos.Form