// generated by Neptune Namespaces v4.x.x
// file: Art.Markdown/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Markdown'))
.addModules({
  Lib:            require('./Lib'),
  StandardImport: require('./StandardImport')
});