// generated by Neptune Namespaces v4.x.x
// file: Art.Markdown/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Markdown',
  (class Markdown extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
