# generated by Neptune Namespaces
# this file: test/tests/art/index.coffee

module.exports =
Art        = require './namespace'
Art.Canvas = require './canvas'
Art.Webgl  = require './webgl'
Art.finishLoad(
  []
)