// generated by Neptune Namespaces v4.x.x
// file: Art.Chat/Client/index.js

(module.exports = require('./namespace'))

.addModules({
  Main:       require('./Main'),
  Palette:    require('./Palette'),
  StyleProps: require('./StyleProps')
});
require('./Components');