# generated by Neptune Namespaces
# file: src/art/engine_remote/namespace.coffee

Art = require '../namespace'
module.exports = Art.EngineRemote ||
class Art.EngineRemote extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.EngineRemote"

Art.addNamespace Art.EngineRemote