# generated by Neptune Namespaces
# file: art/index.coffee

module.exports =
Art                      = require './namespace'
Art.React                = require './react'
Art.ReactSpecializations = require './react_specializations'
Art.finishLoad(
  []
)