// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Canvas/index.js

(module.exports = require('./namespace'))

.addModules({
  Bitmap:            require('./Bitmap'),
  Bitmap2:           require('./Bitmap2'),
  BitmapBase:        require('./BitmapBase'),
  Clipping:          require('./Clipping'),
  CommonBitmapTests: require('./CommonBitmapTests'),
  CompositeModes:    require('./CompositeModes'),
  DrawGradient:      require('./DrawGradient'),
  FillShape:         require('./FillShape'),
  GoogleFontLoader:  require('./GoogleFontLoader'),
  GradientFillStyle: require('./GradientFillStyle'),
  StackBlur:         require('./StackBlur'),
  Stroke:            require('./Stroke'),
  Tools:             require('./Tools')
});