# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Canvas/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Bitmap:            require './Bitmap'           
  BitmapBase:        require './BitmapBase'       
  Clipping:          require './Clipping'         
  CommonBitmapTests: require './CommonBitmapTests'
  DrawGradient:      require './DrawGradient'     
  FillShape:         require './FillShape'        
  GoogleFontLoader:  require './GoogleFontLoader' 
  GradientFillStyle: require './GradientFillStyle'
  StackBlur:         require './StackBlur'        
  Stroke:            require './Stroke'           