# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Canvas/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Canvas', class Canvas extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
