// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Canvas/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Canvas',
  (class Canvas extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
