// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Core/index.js

(module.exports = require('./namespace'))

.addModules({
  Filters:             require('./Filters'),
  KeyFieldsMixin:      require('./KeyFieldsMixin'),
  NiceStackTraces:     require('./NiceStackTraces'),
  PrefetchedRecords:   require('./PrefetchedRecords'),
  RequestResponseBase: require('./RequestResponseBase'),
  RestClientLib:       require('./RestClientLib'),
  Session:             require('./Session'),
  Stack:               require('./Stack')
});
require('./Pipeline');