# generated by Neptune Namespaces
# this file: test/tests/art/canvas/index.coffee

module.exports =
Canvas                   = require './namespace'
Canvas.AssetLoader       = require './asset_loader'
Canvas.Bitmap            = require './bitmap'
Canvas.Clipping          = require './clipping'
Canvas.CommonBitmapTests = require './common_bitmap_tests'
Canvas.GoogleFontLoader  = require './google_font_loader'
Canvas.GradientFillStyle = require './gradient_fill_style'
Canvas.StackBlur         = require './stack_blur'
Canvas.finishLoad(
  ["AssetLoader","Bitmap","Clipping","CommonBitmapTests","GoogleFontLoader","GradientFillStyle","StackBlur"]
)