# generated by Neptune Namespaces v2.x.x
# file: tests/art/canvas/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Bitmap:            require './bitmap'             
  BitmapBase:        require './BitmapBase'         
  Clipping:          require './clipping'           
  CommonBitmapTests: require './common_bitmap_tests'
  DrawGradient:      require './draw_gradient'      
  GoogleFontLoader:  require './google_font_loader' 
  GradientFillStyle: require './gradient_fill_style'
  StackBlur:         require './stack_blur'         