# generated by Neptune Namespaces v0.5
# file: tests/art/canvas/namespace.coffee

Art = require '../namespace'
module.exports = Art.Canvas ||
Art.addNamespace 'Canvas', class Canvas extends Neptune.Base
  ;