# generated by Neptune Namespaces v1.x.x
# file: tests/art/canvas/namespace.coffee

Art = require '../namespace'
module.exports = Art.Canvas ||
Art.addNamespace 'Canvas', class Canvas extends Neptune.Base
  ;