# generated by Neptune Namespaces v0.5
# file: art/flux/db/index.coffee

module.exports = require './namespace'
.addModules
  FluxDbModelBase:  require './flux_db_model_base' 
  FluxDbModel:      require './flux_db_model'      
  FluxDbQueryModel: require './flux_db_query_model'