# generated by Neptune Namespaces
# file: art/flux/db/index.coffee

(module.exports = require './namespace')
.addModules
  FluxDbModel:      require './flux_db_model'
  FluxDbModelBase:  require './flux_db_model_base'
  FluxDbQueryModel: require './flux_db_query_model'
