# generated by Neptune Namespaces
# this file: src/art/flux/db/index.coffee

module.exports =
Db                  = require './namespace'
Db.FluxDbModel      = require './flux_db_model'
Db.FluxDbModelBase  = require './flux_db_model_base'
Db.FluxDbQueryModel = require './flux_db_query_model'
Db.finishLoad(
  ["FluxDbModel","FluxDbModelBase","FluxDbQueryModel"]
)