# generated by Neptune Namespaces
# this file: src/art/engine/receiver/index.coffee

module.exports =
Receiver          = require './namespace'
Receiver.Receiver = require './receiver'
Receiver.finishLoad(
  ["Receiver"]
)