# generated by Neptune Namespaces
# file: art/engine/receiver/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Receiver ||
Engine.addNamespace class Receiver extends Neptune.Base
  ;