// generated by Neptune Namespaces v4.x.x
// file: art/engine/receiver/namespace.js

module.exports = require('../namespace').addNamespace(
  'Receiver',
  class Receiver extends Neptune.PackageNamespace {}
);
