# generated by Neptune Namespaces v0.5
# file: art/engine/receiver/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Receiver ||
Engine.addNamespace 'Receiver', class Receiver extends Neptune.Base
  ;