# generated by Neptune Namespaces v3.x.x
# file: art/engine/receiver/namespace.coffee

module.exports = (require '../namespace').addNamespace('Receiver', class Receiver extends Neptune.PackageNamespace)
