// generated by Neptune Namespaces v4.x.x
// file: Art.SuiteServer/Handlers/index.js

(module.exports = require('./namespace'))

.addModules({
  CatchAllHandler: require('./CatchAllHandler'),
  MainAppHandler:  require('./MainAppHandler')
});