# generated by Neptune Namespaces
# file: tests/art/webgl/namespace.coffee

Art = require '../namespace'
module.exports = Art.Webgl ||
class Art.Webgl extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.Webgl"

Art.addNamespace Art.Webgl