# generated by Neptune Namespaces
# this file: tests/art/text/index.coffee

module.exports =
Text         = require './namespace'
Text.Layout  = require './layout'
Text.Metrics = require './metrics'
Text.finishLoad(
  ["Layout","Metrics"]
)