# generated by Neptune Namespaces v0.3.0
# file: tests/art/text/namespace.coffee

Art = require '../namespace'
module.exports = Art.Text ||
Art.addNamespace 'Text', class Text extends Neptune.Base
  ;