# generated by Neptune Namespaces
# file: tests/art/text/namespace.coffee

Art = require '../namespace'
module.exports = Art.Text ||
class Art.Text extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Tests.Art.Text"

Art.addNamespace Art.Text