# generated by Neptune Namespaces v1.x.x
# file: tests/art/text/namespace.coffee

Art = require '../namespace'
module.exports = Art.Text ||
Art.addNamespace 'Text', class Text extends Neptune.Base
  ;