// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuth/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./AppKitAuth'))
.addModules({
  Lib:            require('./Lib'),
  StandardImport: require('./StandardImport')
});
require('./Pipelines');