// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuth/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.AppKitAuth',
  (class AppKitAuth extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Pipelines/namespace');