// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/index.js

(module.exports = require('./namespace'))

.addModules({
  Config:           require('./Config'),
  PipelineRegistry: require('./PipelineRegistry'),
  StandardImport:   require('./StandardImport')
});
require('./ClientServer');