// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Chat/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Chat',
  (class Chat extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
