// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServer/Pipelines/Transition/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Transition');
