// generated by Neptune Namespaces v4.x.x
// file: tests/Art.App.Kit.Auth/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.App.Kit.Auth',
  (class Auth extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
