// generated by Neptune Namespaces v4.x.x
// file: Art.Canvas/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Canvas'))
.addModules({
  Bitmap:            require('./Bitmap'),
  BitmapBase:        require('./BitmapBase'),
  CompositeModes:    require('./CompositeModes'),
  FontLoader:        require('./FontLoader'),
  GoogleFontLoader:  require('./GoogleFontLoader'),
  GradientFillStyle: require('./GradientFillStyle'),
  MipmapCache:       require('./MipmapCache'),
  Paths:             require('./Paths'),
  StackBlur:         require('./StackBlur'),
  Tools:             require('./Tools')
});