// generated by Neptune Namespaces v4.x.x
// file: Art.Canvas/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.Canvas',
  (class Canvas extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
