// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Components'))
.addModules({
  CanvasPath:     require('./CanvasPath'),
  Page:           require('./Page'),
  PhonePreview:   require('./PhonePreview'),
  StandardImport: require('./StandardImport'),
  SwipePager:     require('./SwipePager')
});
require('./AppCore');
require('./InternalComponents');
require('./Lib');
require('./MenuWidgets');
require('./Widgets');