// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Components'))
.addModules({
  AppBodyWithToolbar: require('./AppBodyWithToolbar'),
  CanvasComponent:    require('./CanvasComponent'),
  CanvasPath:         require('./CanvasPath'),
  Page:               require('./Page'),
  PhonePreview:       require('./PhonePreview'),
  SwipePager:         require('./SwipePager')
});
require('./Lib');
require('./Widgets');