# generated by Neptune Namespaces v3.x.x
# file: Art.AppKit/_Client/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CanvasComponent: require './CanvasComponent'
  PhonePreview:    require './PhonePreview'   