// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Components',
  class Components extends Neptune.PackageNamespace {}
);
require('./AppCore/namespace');
require('./InternalComponents/namespace');
require('./Lib/namespace');
require('./MenuWidgets/namespace');
require('./Widgets/namespace');