# generated by Neptune Namespaces v3.x.x
# file: Art/React/_Mixins/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PointerActionsMixin:   require './PointerActionsMixin'  
  PollingComponentMixin: require './PollingComponentMixin'