// generated by Neptune Namespaces v4.x.x
// file: Art/React/_Mixins/index.js

(module.exports = require('./namespace'))

.addModules({
  PointerActionsMixin:   require('./PointerActionsMixin'),
  PollingComponentMixin: require('./PollingComponentMixin')
});