// generated by Neptune Namespaces v4.x.x
// file: Art/React/_Mixins/namespace.js

module.exports = require('../namespace').addNamespace(
  'Mixins',
  class Mixins extends Neptune.PackageNamespace {}
);
