# generated by Neptune Namespaces v0.5
# file: art/react/Core/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Core'
.addModules
  Component:           require './Component'          
  HotStyleProps:       require './HotStyleProps'      
  ReactArtEngineEpoch: require './ReactArtEngineEpoch'
  VirtualElement:      require './VirtualElement'     
  VirtualNode:         require './VirtualNode'        