# generated by Neptune Namespaces v0.5
# file: art/react/Core/namespace.coffee

React = require '../namespace'
module.exports = React.Core ||
React.addNamespace 'Core', class Core extends Neptune.Base
  ;