// generated by Neptune Namespaces v4.x.x
// file: Art.EngineDemos/index.js

(module.exports = require('./namespace'))

.addModules({
  ArtEngineFactories: require('./ArtEngineFactories'),
  Loader:             require('./Loader')
});
require('./Basic');
require('./Clipping');
require('./Form');
require('./PagingScrollElement');
require('./ScrollElementDynamic');