// generated by Neptune Namespaces v4.x.x
// file: Art.EngineDemos/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.EngineDemos',
  (class EngineDemos extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Basic/namespace');
require('./Clipping/namespace');
require('./Form/namespace');
require('./PagingScrollElement/namespace');
require('./ScrollElementDynamic/namespace');