// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Atomic/index.js

(module.exports = require('./namespace'))

.addModules({
  Color:     require('./Color'),
  Matrix:    require('./Matrix'),
  Matrix2:   require('./Matrix2'),
  Perimeter: require('./Perimeter'),
  Point:     require('./Point'),
  Rectangle: require('./Rectangle')
});