# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Atomic/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Atomic', class Atomic extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
