// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Atomic/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Atomic',
  (class Atomic extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
