// generated by Neptune Namespaces v4.x.x
// file: tests/Pointer.Actions.Mixin/namespace.js

module.exports = require('../namespace').addNamespace(
  'Pointer.Actions.Mixin',
  (class Mixin extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
