// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.PointerActionsMixinNamespace/index.js

(module.exports = require('./namespace'))

.addModules({
  PointerActionsMixin: require('./PointerActionsMixin')
});