// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.PointerActionsMixinNamespace/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'ArtSuite.PointerActionsMixinNamespace',
  (class PointerActionsMixinNamespace extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
