# generated by Neptune Namespaces v1.x.x
# file: Art/React/.Mixins/namespace.coffee

React = require '../namespace'
module.exports = React.Mixins ||
React.addNamespace 'Mixins', class Mixins extends Neptune.Base
  ;