// generated by Neptune Namespaces v4.x.x
// file: Art.EngineDemos/PagingScrollElement/namespace.js

module.exports = require('../namespace').addNamespace(
  'PagingScrollElement',
  class PagingScrollElement extends Neptune.PackageNamespace {}
);
