# generated by Neptune Namespaces
# file: art/atomic/index.coffee

(module.exports = require './namespace')
.addModules
  All:       require './all'
  Base:      require './base'
  Color:     require './color'
  Matrix:    require './matrix'
  Perimeter: require './perimeter'
  Point:     require './point'
  Rectangle: require './rectangle'
