# generated by Neptune Namespaces
# this file: src/art/atomic/index.coffee

module.exports =
Atomic           = require './namespace'
Atomic.All       = require './all'
Atomic.Base      = require './base'
Atomic.Color     = require './color'
Atomic.Matrix    = require './matrix'
Atomic.Perimeter = require './perimeter'
Atomic.Point     = require './point'
Atomic.Rectangle = require './rectangle'
Atomic.finishLoad(
  ["All","Base","Color","Matrix","Perimeter","Point","Rectangle"]
  []
)