# generated by Neptune Namespaces v0.3.0
# file: art/atomic/namespace.coffee

Art = require '../namespace'
module.exports = Art.Atomic ||
Art.addNamespace 'Atomic', class Atomic extends Neptune.Base
  ;