# generated by Neptune Namespaces v0.5
# file: art/aws/StreamlinedDynamoDbApi/index.coffee

module.exports = require './namespace'
.addModules
  Common:         require './Common'        
  CreateTableApi: require './CreateTableApi'
  Tools:          require './Tools'         