# generated by Neptune Namespaces v1.x.x
# file: art/aws/StreamlinedDynamoDbApi/namespace.coffee

Aws = require '../namespace'
module.exports = Aws.StreamlinedDynamoDbApi ||
Aws.addNamespace 'StreamlinedDynamoDbApi', class StreamlinedDynamoDbApi extends Neptune.Base
  ;