// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Flux/React/index.js

(module.exports = require('./namespace'))

.addModules({
  ComponentLib:      require('./ComponentLib'),
  FluxComponent:     require('./FluxComponent'),
  FluxComponentTest: require('./FluxComponent.test')
});