# generated by Neptune Namespaces v0.3.0
# file: tests/art/suite/namespace.coffee

Art = require '../namespace'
module.exports = Art.Suite ||
Art.addNamespace 'Suite', class Suite extends Neptune.Base
  ;