# generated by Neptune Namespaces v3.x.x
# file: Art.EngineDemos/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.EngineDemos', class EngineDemos extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Basic/namespace';
require './Clipping/namespace';
require './Form/namespace';
require './PagingScrollElement/namespace'