# generated by Neptune Namespaces
# this file: test/tests/art/index.coffee

module.exports =
Art              = require './namespace'
Art.EngineRemote = require './engine_remote'
Art.finishLoad(
  []
)