// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/Lib/index.js

(module.exports = require('./namespace'))

.addModules({
  AppKitButtonWrapper: require('./AppKitButtonWrapper')
});