// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/Lib/namespace.js

module.exports = require('../namespace').addNamespace(
  'Lib',
  class Lib extends Neptune.PackageNamespace {}
);
