// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/MenuWidgets/index.js

(module.exports = require('./namespace'))

.addModules({
  MenuButton:         require('./MenuButton'),
  MenuEditableText:   require('./MenuEditableText'),
  MenuHeading:        require('./MenuHeading'),
  MenuInfo:           require('./MenuInfo'),
  MenuLib:            require('./MenuLib'),
  MenuLoadingSpinner: require('./MenuLoadingSpinner'),
  MenuSection:        require('./MenuSection'),
  MenuSectionGroup:   require('./MenuSectionGroup'),
  MenuSectionLabel:   require('./MenuSectionLabel'),
  MenuTabbedSection:  require('./MenuTabbedSection'),
  MenuTextEdit:       require('./MenuTextEdit'),
  MenuTextInput:      require('./MenuTextInput'),
  MenuToggle:         require('./MenuToggle'),
  PrimaryMenuButton:  require('./PrimaryMenuButton'),
  StandardImport:     require('./StandardImport')
});
require('./MenuSupportWidgets');