// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/MenuWidgets/namespace.js

module.exports = require('../namespace').addNamespace(
  'MenuWidgets',
  class MenuWidgets extends Neptune.PackageNamespace {}
);
require('./MenuSupportWidgets/namespace');