# generated by Neptune Namespaces v1.x.x
# file: art/canvas/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_canvas'
.addModules
  BitmapBase:        require './bitmap_base'        
  Bitmap:            require './bitmap'             
  FontLoader:        require './FontLoader'         
  GoogleFontLoader:  require './google_font_loader' 
  GradientFillStyle: require './gradient_fill_style'
  Paths:             require './paths'              
  StackBlur:         require './stack_blur'         