# generated by Neptune Namespaces v0.3.0
# file: art/canvas/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_canvas')
.addModules
  Bitmap:            require './bitmap'
  BitmapBase:        require './bitmap_base'
  GoogleFontLoader:  require './google_font_loader'
  GradientFillStyle: require './gradient_fill_style'
  Paths:             require './paths'
  StackBlur:         require './stack_blur'
  StackBlurOriginal: require './stack_blur_original'