# generated by Neptune Namespaces v2.x.x
# file: art/canvas/namespace.coffee

Art = require '../namespace'
module.exports = Art.Canvas ||
Art.addNamespace 'Canvas', class Canvas extends Neptune.Base
  ;
