# generated by Neptune Namespaces
# file: src/art/canvas/namespace.coffee

Art = require '../namespace'
module.exports = Art.Canvas ||
class Art.Canvas extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Canvas"

Art.addNamespace Art.Canvas