# generated by Neptune Namespaces v3.x.x
# file: Art.CanvasPath/Encoding/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Encoding'
.addModules
  EncodingLib:  require './EncodingLib' 
  XbdFactories: require './XbdFactories'