# generated by Neptune Namespaces
# this file: test/tests/art/engine_remote/index.coffee

module.exports =
EngineRemote                = require './namespace'
EngineRemote.Remote         = require './remote'
EngineRemote.RemoteReceiver = require './remote_receiver'
EngineRemote.finishLoad(
  ["Remote","RemoteReceiver"]
)