# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.Elasticsearch/Pipelines/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ElasticsearchGlobal:           require './ElasticsearchGlobal'          
  ElasticsearchPipeline:         require './ElasticsearchPipeline'        
  ElasticsearchPipelineBase:     require './ElasticsearchPipelineBase'    
  MirroredElasticsearchPipeline: require './MirroredElasticsearchPipeline'