// generated by Neptune Namespaces v4.x.x
// file: Art.EryExtensions.Elasticsearch/Pipelines/index.js

(module.exports = require('./namespace'))

.addModules({
  ElasticsearchGlobal:           require('./ElasticsearchGlobal'),
  ElasticsearchPipeline:         require('./ElasticsearchPipeline'),
  ElasticsearchPipelineBase:     require('./ElasticsearchPipelineBase'),
  MirroredElasticsearchPipeline: require('./MirroredElasticsearchPipeline')
});