# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.Elasticsearch/Pipelines/namespace.coffee

module.exports = (require '../namespace').addNamespace('Pipelines', class Pipelines extends Neptune.PackageNamespace)
