# generated by Neptune Namespaces v3.x.x
# file: Art.EngineDemos/ScrollElementDynamic/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScrollElementDynamic', class ScrollElementDynamic extends Neptune.PackageNamespace)
