// generated by Neptune Namespaces v4.x.x
// file: SimpleClientServer/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'SimpleClientServer',
  (class SimpleClientServer extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Configurations/namespace');
require('./Pipelines/namespace');