// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/MenuWidgets/MenuSupportWidgets/index.js

(module.exports = require('./namespace'))

.addModules({
  IconAndText: require('./IconAndText')
});