// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/MenuWidgets/MenuSupportWidgets/namespace.js

module.exports = require('../namespace').addNamespace(
  'MenuSupportWidgets',
  class MenuSupportWidgets extends Neptune.PackageNamespace {}
);
