# generated by Neptune Namespaces v1.x.x
# file: Art/Suite/App/Client/namespace.coffee

App = require '../namespace'
module.exports = App.Client ||
App.addNamespace 'Client', class Client extends Neptune.Base
  ;