# generated by Neptune Namespaces v3.x.x
# file: Art.Canvas/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Canvas'
.addModules
  Bitmap:            require './Bitmap'           
  BitmapBase:        require './BitmapBase'       
  FontLoader:        require './FontLoader'       
  GoogleFontLoader:  require './GoogleFontLoader' 
  GradientFillStyle: require './GradientFillStyle'
  Paths:             require './Paths'            
  StackBlur:         require './StackBlur'        
  Tools:             require './Tools'            