# generated by Neptune Namespaces
# file: perf/perfs/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Perfs ||
class Neptune.Perfs extends Neptune.Base
  @namespace: Neptune
  @namespacePath: "Neptune.Perfs"

Neptune.addNamespace Neptune.Perfs