// generated by Neptune Namespaces v4.x.x
// file: perfs/namespace.js

module.exports = module.exports =  require('neptune-namespaces-runtime').vivifySubnamespace('Perfs');
require('./art/namespace');