# generated by Neptune Namespaces v0.3.0
# file: perfs/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Perfs ||
Neptune.addNamespace 'Perfs', class Perfs extends Neptune.Base
  ;