# generated by Neptune Namespaces v2.x.x
# file: art/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Art ||
Neptune.addNamespace 'Art', class Art extends Neptune.Base
  ;
require './canvas/namespace'