// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/InternalComponents/namespace.js

module.exports = require('../namespace').addNamespace(
  'InternalComponents',
  class InternalComponents extends Neptune.PackageNamespace {}
);
