# generated by Neptune Namespaces v1.x.x
# file: tests/art/flux/core/index.coffee

module.exports = require './namespace'
.addModules
  FluxModel: require './flux_model'
  FluxStore: require './flux_store'