# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Flux/Core/index.coffee

module.exports = require './namespace'
.addModules
  FluxModel: require './FluxModel'
  FluxStore: require './FluxStore'