# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Flux/Core/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  FluxModel:              require './FluxModel'             
  FluxStore:              require './FluxStore'             
  FluxSubscriptionsMixin: require './FluxSubscriptionsMixin'