# generated by Neptune Namespaces v0.1.0
# file: tests/art/flux/core/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Core ||
Flux.addNamespace class Core extends Neptune.Base
  ;