# generated by Neptune Namespaces v1.x.x
# file: tests/art/flux/core/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Core ||
Flux.addNamespace 'Core', class Core extends Neptune.Base
  ;