# generated by Neptune Namespaces
# file: test/tests/art/flux/core/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Core ||
class Flux.Core extends Neptune.Base
  @namespace: Flux
  @namespacePath: "Neptune.Tests.Art.Flux.Core"

Flux.addNamespace Flux.Core