# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Flux/Core/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Core ||
Flux.addNamespace 'Core', class Core extends Neptune.Base
  ;
