# generated by Neptune Namespaces
# this file: perf/perfs/art/atomic/index.coffee

module.exports =
Atomic           = require './namespace'
Atomic.Color     = require './color'
Atomic.Matrix    = require './matrix'
Atomic.Point     = require './point'
Atomic.Rectangle = require './rectangle'
Atomic.finishLoad(
  ["Color","Matrix","Point","Rectangle"]
)