// generated by Neptune Namespaces v4.x.x
// file: perfs/art/atomic/index.js

(module.exports = require('./namespace'))

.addModules({
  Color:     require('./color'),
  Matrix:    require('./matrix'),
  Point:     require('./point'),
  Rectangle: require('./rectangle')
});