# generated by Neptune Namespaces v1.x.x
# file: perfs/art/atomic/index.coffee

module.exports = require './namespace'
.addModules
  Color:     require './color'    
  Matrix:    require './matrix'   
  Point:     require './point'    
  Rectangle: require './rectangle'