// generated by Neptune Namespaces v4.x.x
// file: perfs/art/atomic/namespace.js

module.exports = require('../namespace').addNamespace(
  'Atomic',
  (class Atomic extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../package.json'))
);
