# generated by Neptune Namespaces v3.x.x
# file: perfs/art/atomic/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Atomic', class Atomic extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
