# generated by Neptune Namespaces
# file: perf/perfs/art/atomic/namespace.coffee

Art = require '../namespace'
module.exports = Art.Atomic ||
class Art.Atomic extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Perfs.Art.Atomic"

Art.addNamespace Art.Atomic