# generated by Neptune Namespaces v0.5
# file: perfs/art/atomic/namespace.coffee

Art = require '../namespace'
module.exports = Art.Atomic ||
Art.addNamespace 'Atomic', class Atomic extends Neptune.Base
  ;