// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/_PrivateWidgets/index.js

(module.exports = require('./namespace'))

.addModules({
  ActivityBadge:         require('./ActivityBadge'),
  Spinner:               require('./Spinner'),
  StandardImport:        require('./StandardImport'),
  StatusWidgets:         require('./StatusWidgets'),
  SubmitField:           require('./SubmitField'),
  TabButton:             require('./TabButton'),
  TextInputSubmitButton: require('./TextInputSubmitButton')
});