// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/_PrivateWidgets/namespace.js

module.exports = require('../namespace').addNamespace(
  'PrivateWidgets',
  class PrivateWidgets extends Neptune.PackageNamespace {}
);
