// generated by Neptune Namespaces v4.x.x
// file: Art.Suite/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Suite',
  (class Suite extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
