# generated by Neptune Namespaces v3.x.x
# file: Art.Suite/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Suite', class Suite extends Neptune.PackageNamespace
  @version: require('../../package.json').version
