// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/NativePreview/namespace.js

module.exports = require('../namespace').addNamespace(
  'NativePreview',
  class NativePreview extends Neptune.PackageNamespace {}
);
require('./Components/namespace');