# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.DynamoDb/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DynamoDbPipeline: require './DynamoDbPipeline'