# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.DynamoDb/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.EryExtensions.DynamoDb', class DynamoDb extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
