# generated by Neptune Namespaces v3.x.x
# file: Art.AppKit/Style/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  TextPalette: require './TextPalette'
  TextStyles:  require './TextStyles' 