// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/Style/index.js

(module.exports = require('./namespace'))

.addModules({
  AppPalette:  require('./AppPalette'),
  TextPalette: require('./TextPalette'),
  TextStyles:  require('./TextStyles')
});