// generated by Neptune Namespaces v4.x.x
// file: tests/SimpleClientServer/namespace.js

module.exports = require('../namespace').addNamespace(
  'SimpleClientServer',
  (class SimpleClientServer extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
