// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServerFlux/index.js

(module.exports = require('./namespace'))

.addModules({
  DataUpdatesFilter: require('./DataUpdatesFilter')
});