// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServerFlux/namespace.js

module.exports = require('../namespace').addNamespace(
  'ClientServerFlux',
  class ClientServerFlux extends Neptune.PackageNamespace {}
);
