# generated by Neptune Namespaces v3.x.x
# file: Art.CanvasPath/Extractor/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Extractor'
.addModules
  StandardImport:   require './StandardImport'  
  SvgPathExtractor: require './SvgPathExtractor'