// generated by Neptune Namespaces v4.x.x
// file: Art.CanvasPath/Extractor/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Extractor'))
.addModules({
  StandardImport:   require('./StandardImport'),
  SvgPathExtractor: require('./SvgPathExtractor')
});