// generated by Neptune Namespaces v4.x.x
// file: Art.CanvasPath/Extractor/namespace.js

module.exports = require('../namespace').addNamespace(
  'Extractor',
  class Extractor extends Neptune.PackageNamespace {}
);
