# generated by Neptune Namespaces v3.x.x
# file: Art.CanvasPath/Extractor/namespace.coffee

module.exports = (require '../namespace').addNamespace('Extractor', class Extractor extends Neptune.PackageNamespace)
