// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./AppKit'))
.addModules({
  StandardImport: require('./StandardImport')
});
require('./Style');