# generated by Neptune Namespaces v3.x.x
# file: Art.AppKit/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './AppKit'
.addModules
  StandardImport: require './StandardImport'
require './Style'