// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.AppKit',
  (class AppKit extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Lib/namespace');
require('./Style/namespace');