// generated by Neptune Namespaces v4.x.x
// file: Art.App/Tools/Commands/namespace.js

module.exports = require('../namespace').addNamespace(
  'Commands',
  class Commands extends Neptune.PackageNamespace {}
);
