// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuthDemos/namespace.js

module.exports = module.exports =  require('neptune-namespaces-runtime').vivifySubnamespace('Art.AppKitAuthDemos');
require('./Basic/namespace');