// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/KitchenSink/Components/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Components');
require('./Pages/namespace');