# generated by Neptune Namespaces v2.x.x
# file: Art/Flux/Core/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  FluxEntry:              require './FluxEntry'             
  FluxModel:              require './FluxModel'             
  FluxStore:              require './FluxStore'             
  FluxSubscriptionsMixin: require './FluxSubscriptionsMixin'
  ModelRegistry:          require './ModelRegistry'         