# generated by Neptune Namespaces v1.x.x
# file: Art/Flux/Core/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Core ||
Flux.addNamespace 'Core', class Core extends Neptune.Base
  ;