// generated by Neptune Namespaces v4.x.x
// file: Art.EngineDemos/Basic/namespace.js

module.exports = require('../namespace').addNamespace(
  'Basic',
  class Basic extends Neptune.PackageNamespace {}
);
