# generated by Neptune Namespaces
# this file: test/tests/flux/index.coffee

module.exports =
Flux        = require './namespace'
Flux.Core   = require './core'
Flux.Models = require './models'
Flux.React  = require './react'
Flux.finishLoad(
  []
)