# generated by Neptune Namespaces
# file: test/tests/flux/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Flux ||
class Tests.Flux extends Neptune.Base
  @namespace: Tests
  @namespacePath: "Neptune.Tests.Flux"

Tests.addNamespace Tests.Flux