// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuthDemos/Basic/namespace.js

module.exports = require('../namespace').addNamespace(
  'Basic',
  (class Basic extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
