// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuthDemos/Basic/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Basic');
require('./Pipelines/namespace');