# How to run an Elasticsearch 7 single node cluster for local development using Docker Compose?
# FROM: https://medium.com/@TimvanBaarsen/how-to-run-an-elasticsearch-7-x-single-node-cluster-for-local-development-using-docker-compose-2b7ab73d8b82
version: "3.7"
# SBD NOTES:
# all docker versions: https://www.docker.elastic.co/r/elasticsearch?limit=50&offset=300&show_snapshots=false
# My code works with 5.*
# Sounds like 6.* deprecated some of my code
# And 7.* removed it
# Unfortunately, there aren't amd64 verions before v7.
# 5.6.2 crashs in emulation
# maybe the last version of 5 will work?
# maybe the last version of 6 will work?
# maybe I hack an elastic-search version option in my code, support the latest, and hope for the best with v5 support?
services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    platform: linux/amd64
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    platform: linux/amd64
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
