// generated by Neptune Namespaces v4.x.x
// file: tests/ArtSuite.Models/index.js

(module.exports = require('./namespace'))

.addModules({
  ApplicationState:                require('./ApplicationState'),
  FluxModel:                       require('./FluxModel'),
  FluxStoreTest:                   require('./FluxStore.test'),
  FluxSubscriptionMixinTest:       require('./FluxSubscriptionMixin.test'),
  FluxSubscriptionMixinBasicsTest: require('./FluxSubscriptionMixinBasics.test')
});