// generated by Neptune Namespaces v4.x.x
// file: tests/ArtSuite.Models/namespace.js

module.exports = require('../namespace').addNamespace(
  'ArtSuite.Models',
  class Models extends Neptune.PackageNamespace {}
);
