// generated by Neptune Namespaces v4.x.x
// file: Art.ColorExtractor/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./ColorExtractor'))
.addModules({
  Vibrant: require('./Vibrant')
});