// generated by Neptune Namespaces v4.x.x
// file: Art.ColorExtractor/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.ColorExtractor',
  (class ColorExtractor extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
