# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.IndexedDb/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  IndexedDbPipeline: require './IndexedDbPipeline'
  StandardImport:    require './StandardImport'   