# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.IndexedDb/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.EryExtensions.IndexedDb', class IndexedDb extends Neptune.PackageNamespace
  @version: require('../../package.json').version
