# generated by Neptune Namespaces
# file: perf/perfs/art/namespace.coffee

Perfs = require '../namespace'
module.exports = Perfs.Art ||
class Perfs.Art extends Neptune.Base
  @namespace: Perfs
  @namespacePath: "Neptune.Perfs.Art"

Perfs.addNamespace Perfs.Art