# generated by Neptune Namespaces v2.x.x
# file: perfs/art/namespace.coffee

Perfs = require '../namespace'
module.exports = Perfs.Art ||
Perfs.addNamespace 'Art', class Art extends Neptune.Base
  ;
require './atomic/namespace'