// generated by Neptune Namespaces v4.x.x
// file: Art/React/Core/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Core'))
.addModules({
  Component:           require('./Component'),
  HotStyleProps:       require('./HotStyleProps'),
  PropFieldsMixin:     require('./PropFieldsMixin'),
  ReactArtEngineEpoch: require('./ReactArtEngineEpoch'),
  StateFieldsMixin:    require('./StateFieldsMixin'),
  VirtualElement:      require('./VirtualElement'),
  VirtualNode:         require('./VirtualNode')
});