# generated by Neptune Namespaces v3.x.x
# file: Art/React/Core/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Core'
.addModules
  Component:           require './Component'          
  HotStyleProps:       require './HotStyleProps'      
  ReactArtEngineEpoch: require './ReactArtEngineEpoch'
  StateFieldsMixin:    require './StateFieldsMixin'   
  VirtualElement:      require './VirtualElement'     
  VirtualNode:         require './VirtualNode'        