# generated by Neptune Namespaces v3.x.x
# file: Art/React/Core/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Core', class Core extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
