# generated by Neptune Namespaces v3.x.x
# file: perfs/Art/Canvas/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Bitmap: require './Bitmap'
  Taint:  require './Taint' 