// generated by Neptune Namespaces v4.x.x
// file: perfs/Art/Canvas/namespace.js

module.exports = require('../namespace').addNamespace(
  'Canvas',
  class Canvas extends Neptune.PackageNamespace {}
);
