// generated by Neptune Namespaces v4.x.x
// file: Art.Chat/_Client/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  Button:      require('./Button'),
  ChatMessage: require('./ChatMessage'),
  ChatView:    require('./ChatView'),
  Lobby:       require('./Lobby')
});