# generated by Neptune Namespaces v1.x.x
# file: assets/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Assets ||
Neptune.addNamespace 'Assets', class Assets extends Neptune.Base
  ;