# generated by Neptune Namespaces v3.x.x
# file: assets/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Assets', class Assets extends Neptune.PackageNamespace
  @version: require('../../package.json').version
