// generated by Neptune Namespaces v4.x.x
// file: jest/index.js

(module.exports = require('./namespace'))

.addModules({
  ColorTest:      require('./Color.test'),
  MatrixTest:     require('./Matrix.test'),
  Matrix2Test:    require('./Matrix2.test'),
  PerimeterTest:  require('./Perimeter.test'),
  PointTest:      require('./Point.test'),
  RectangleTest:  require('./Rectangle.test'),
  StandardImport: require('./StandardImport')
});