# generated by Neptune Namespaces v3.x.x
# file: Art/React/namespace.coffee

module.exports = (require '../namespace').addNamespace 'React', class React extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './Core/namespace'