// generated by Neptune Namespaces v4.x.x
// file: Art/React/namespace.js

module.exports = require('../namespace').addNamespace(
  'React',
  (class React extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Core/namespace');