// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.Models/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Models'))
.addModules({
  FluxEntry:              require('./FluxEntry'),
  FluxModel:              require('./FluxModel'),
  FluxSubscriptionsMixin: require('./FluxSubscriptionsMixin'),
  Lib:                    require('./Lib'),
  ModelRegistry:          require('./ModelRegistry'),
  StandardImport:         require('./StandardImport'),
  Store:                  require('./Store')
});