// generated by Neptune Namespaces v4.x.x
// file: Art.Flux/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Flux'))
.addModules({
  FluxEntry:              require('./FluxEntry'),
  FluxModel:              require('./FluxModel'),
  FluxStore:              require('./FluxStore'),
  FluxSubscriptionsMixin: require('./FluxSubscriptionsMixin'),
  ModelRegistry:          require('./ModelRegistry')
});