// generated by Neptune Namespaces v4.x.x
// file: Art.Mailgun/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Mailgun'))
.addModules({
  Config: require('./Config')
});