// generated by Neptune Namespaces v4.x.x
// file: tests/art/engine/index.js

(module.exports = require('./namespace'))

.addModules({
  Receiver: require('./receiver'),
  Remote:   require('./remote')
});