# generated by Neptune Namespaces v3.x.x
# file: tests/art/engine/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Receiver: require './receiver'
  Remote:   require './remote'  