// generated by Neptune Namespaces v4.x.x
// file: tests/art/engine/namespace.js

module.exports = require('../namespace').addNamespace(
  'Engine',
  (class Engine extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../package.json'))
);
