# generated by Neptune Namespaces v2.x.x
# file: Art/Ery/Aws/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Aws'
.addModules
  DynamoDbPipeline: require './DynamoDbPipeline'