# generated by Neptune Namespaces v1.x.x
# file: Art/Ery/Aws/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Aws'
.addModules
  DynamoDbPipeline: require './DynamoDbPipeline'