// generated by Neptune Namespaces v4.x.x
// file: Art.EngineDemos/ScrollElementDynamic/namespace.js

module.exports = require('../namespace').addNamespace(
  'ScrollElementDynamic',
  class ScrollElementDynamic extends Neptune.PackageNamespace {}
);
