# generated by Neptune Namespaces v1.x.x
# file: perfs/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Perfs ||
Neptune.addNamespace 'Perfs', class Perfs extends Neptune.Base
  ;