// generated by Neptune Namespaces v4.x.x
// file: Art/Flux/Core/index.js

(module.exports = require('./namespace'))

.addModules({
  FluxEntry:              require('./FluxEntry'),
  FluxModel:              require('./FluxModel'),
  FluxStore:              require('./FluxStore'),
  FluxSubscriptionsMixin: require('./FluxSubscriptionsMixin'),
  ModelRegistry:          require('./ModelRegistry')
});