# generated by Neptune Namespaces
# this file: src/art/engine/index.coffee

module.exports =
Engine        = require './namespace'
Engine.Demos  = require './demos'
Engine.Loader = require './loader'
Engine.finishLoad(
  ["Loader"]
)