# generated by Neptune Namespaces v3.x.x
# file: art/engine/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Engine', class Engine extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './demos/namespace'