// generated by Neptune Namespaces v4.x.x
// file: Art.EryExtensions.Elasticsearch/Pipelines/_Caf-WIP/index.js

(module.exports = require('./namespace'))

.addModules({
  ElasticsearchGlobal:       require('./ElasticsearchGlobal'),
  ElasticsearchPipelineBase: require('./ElasticsearchPipelineBase')
});