// generated by Neptune Namespaces v4.x.x
// file: test/Art.Components/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  BasicsTest:              require('./Basics.test'),
  CanUpdateFromTest:       require('./CanUpdateFrom.test'),
  ChildrenPropTest:        require('./ChildrenProp.test'),
  CloneTest:               require('./Clone.test'),
  CoComponnentUpdatesTest: require('./CoComponnentUpdates.test'),
  InspectionTest:          require('./Inspection.test'),
  LifeCycleTest:           require('./LifeCycle.test'),
  RefsTest:                require('./Refs.test'),
  RootElementUpdatesTest:  require('./RootElementUpdates.test'),
  StateTest:               require('./State.test'),
  StateFieldsTest:         require('./StateFields.test'),
  UpdateFromTest:          require('./UpdateFrom.test'),
  WrapperComponentsTest:   require('./WrapperComponents.test')
});