// generated by Neptune Namespaces v4.x.x
// file: test/index.js

(module.exports = require('./namespace'))

.addModules({
  ApplicationState:                require('./ApplicationState'),
  FluxModelTest:                   require('./FluxModel.test'),
  FluxSubscriptionMixinTest:       require('./FluxSubscriptionMixin.test'),
  FluxSubscriptionMixinBasicsTest: require('./FluxSubscriptionMixinBasics.test'),
  LibTest:                         require('./Lib.test'),
  StandardImport:                  require('./StandardImport'),
  StoreTest:                       require('./Store.test')
});