// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuthDemos/Basic/Pipelines/namespace.js

module.exports = require('../namespace').addNamespace(
  'Pipelines',
  (class Pipelines extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../package.json'))
);
