// generated by Neptune Namespaces v4.x.x
// file: tests/Art.FrameStats/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.FrameStats',
  (class FrameStats extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
