// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/AppCore/index.js

(module.exports = require('./namespace'))

.addModules({
  App:                require('./App'),
  AppBodyWithToolbar: require('./AppBodyWithToolbar'),
  CanvasComponent:    require('./CanvasComponent'),
  Toolbar:            require('./Toolbar')
});