// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Components/AppCore/namespace.js

module.exports = require('../namespace').addNamespace(
  'AppCore',
  class AppCore extends Neptune.PackageNamespace {}
);
