// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitAuth/_Client/Components/namespace.js

module.exports = require('../namespace').addNamespace(
  'Components',
  class Components extends Neptune.PackageNamespace {}
);
