// generated by Neptune Namespaces v4.x.x
// file: tests/Art/Flux/React/namespace.js

module.exports = require('../namespace').addNamespace(
  'React',
  class React extends Neptune.PackageNamespace {}
);
