// generated by Neptune Namespaces v4.x.x
// file: SimpleClientServer/Configurations/namespace.js

module.exports = require('../namespace').addNamespace(
  'Configurations',
  class Configurations extends Neptune.PackageNamespace {}
);
