// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/KitchenSinkDemo/namespace.js

module.exports = require('../namespace').addNamespace(
  'KitchenSinkDemo',
  class KitchenSinkDemo extends Neptune.PackageNamespace {}
);
require('./Components/namespace');