# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Aws/DynamoDbPipeline/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:              require './Basics'             
  CrossPipelineEvents: require './CrossPipelineEvents'