// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Aws/DynamoDbPipeline/index.js

(module.exports = require('./namespace'))

.addModules({
  Basics:              require('./Basics'),
  CrossPipelineEvents: require('./CrossPipelineEvents'),
  Indexes:             require('./Indexes')
});