# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Aws/DynamoDbPipeline/namespace.coffee

module.exports = (require '../namespace').addNamespace('DynamoDbPipeline', class DynamoDbPipeline extends Neptune.PackageNamespace)
