// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Aws/DynamoDbPipeline/namespace.js

module.exports = require('../namespace').addNamespace(
  'DynamoDbPipeline',
  class DynamoDbPipeline extends Neptune.PackageNamespace {}
);
