# generated by Neptune Namespaces v3.x.x
# file: Art.App/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Client: require './Client'
  Node:   require './Node'  
  Server: require './Server'
require './Tools'