// generated by Neptune Namespaces v4.x.x
// file: Art.App/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.App',
  (class App extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Tools/namespace');