# generated by Neptune Namespaces v3.x.x
# file: Art.App/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.App', class App extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Tools/namespace'