// generated by Neptune Namespaces v4.x.x
// file: Art.Components.Engine/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Engine'))
.addModules({
  EngineVirtualElement: require('./EngineVirtualElement'),
  StandardImport:       require('./StandardImport')
});