// generated by Neptune Namespaces v4.x.x
// file: Art.Components.Engine/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.Components.Engine',
  (class Engine extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
