// generated by Neptune Namespaces v4.x.x
// file: Art.AppKitDemos/Minimum/namespace.js

module.exports = require('../namespace').addNamespace(
  'Minimum',
  class Minimum extends Neptune.PackageNamespace {}
);
