# generated by Neptune Namespaces v3.x.x
# file: tests2/Art/Atomic/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Color:     require './Color'    
  Matrix:    require './Matrix'   
  Matrix2:   require './Matrix2'  
  Perimeter: require './Perimeter'
  Point:     require './Point'    
  Rectangle: require './Rectangle'