# generated by Neptune Namespaces
# this file: src/art/engine/remote/index.coffee

module.exports =
Remote          = require './namespace'
Remote.Receiver = require './receiver'
Remote.Remote   = require './remote'
Remote.finishLoad(
  ["Receiver","Remote"]
)