// generated by Neptune Namespaces v4.x.x
// file: art/engine/remote/namespace.js

module.exports = require('../namespace').addNamespace(
  'Remote',
  class Remote extends Neptune.PackageNamespace {}
);
