# generated by Neptune Namespaces v0.5
# file: art/engine/remote/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Remote ||
Engine.addNamespace 'Remote', class Remote extends Neptune.Base
  ;