# generated by Neptune Namespaces
# file: src/art/engine/remote/namespace.coffee

Engine = require '../namespace'
module.exports = Engine.Remote ||
class Engine.Remote extends Neptune.Base
  @namespace: Engine
  @namespacePath: "Neptune.Art.Engine.Remote"

Engine.addNamespace Engine.Remote