// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/Both/Filters/index.js

(module.exports = require('./namespace'))

.addModules({
  DatabaseFilters:         require('./DatabaseFilters'),
  LinkFieldsFilter:        require('./LinkFieldsFilter'),
  LinkFieldsFilter2:       require('./LinkFieldsFilter2'),
  LinkFieldsFilterInclude: require('./LinkFieldsFilterInclude'),
  PrefetchedRecordsCache:  require('./PrefetchedRecordsCache'),
  TimestampFilter:         require('./TimestampFilter'),
  UniqueIdFilter:          require('./UniqueIdFilter'),
  ValidationFilter:        require('./ValidationFilter')
});