// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Components.Engine/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Components.Engine',
  (class Engine extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
