# generated by Neptune Namespaces v1.x.x
# file: Art/Flux/.DepricatedModels/index.coffee

module.exports = require './namespace'
.addModules
  VolatileModel:      require './VolatileModel'     
  VolatileQueryModel: require './VolatileQueryModel'
  VolatileStore:      require './VolatileStore'     
require './Db'