// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Elasticsearch/index.js

(module.exports = require('./namespace'))

.addModules({
  ElasticsearchGlobal:           require('./ElasticsearchGlobal'),
  GrandparentChild:              require('./GrandparentChild'),
  Hashtags:                      require('./Hashtags'),
  IndexEntry:                    require('./IndexEntry'),
  MirroredElasticsearchPipeline: require('./MirroredElasticsearchPipeline'),
  ParentChild:                   require('./ParentChild')
});