# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Elasticsearch/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.EryExtensions.Elasticsearch', class Elasticsearch extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
