// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EryExtensions.Elasticsearch/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.EryExtensions.Elasticsearch',
  (class Elasticsearch extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
