# generated by Neptune Namespaces v3.x.x
# file: Art.AppKit/_Client/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  AppKitPresentationState: require './AppKitPresentationState'
  AppKitViewState:         require './AppKitViewState'        