// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  AppKitPresentationState: require('./AppKitPresentationState'),
  AppKitViewState:         require('./AppKitViewState'),
  PageStack:               require('./PageStack')
});