// generated by Neptune Namespaces v4.x.x
// file: Art.AppKit/_Client/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  AgeString:               require('./AgeString'),
  AppKitPresentationState: require('./AppKitPresentationState'),
  AppKitViewState:         require('./AppKitViewState'),
  CurrentSession:          require('./CurrentSession'),
  PageStack:               require('./PageStack'),
  UrlBarState:             require('./UrlBarState'),
  VersionCheck:            require('./VersionCheck')
});