# generated by Neptune Namespaces v0.5
# file: tests/art/flux/models/index.coffee

module.exports = require './namespace'
.addModules
  VolatileModel: require './volatile_model'
  VolatileStore: require './volatile_store'