# generated by Neptune Namespaces
# this file: test/tests/art/flux/models/index.coffee

module.exports =
Models               = require './namespace'
Models.VolatileModel = require './volatile_model'
Models.VolatileStore = require './volatile_store'
Models.finishLoad(
  ["VolatileModel","VolatileStore"]
)