# generated by Neptune Namespaces v0.3.0
# file: tests/art/flux/models/namespace.coffee

Flux = require '../namespace'
module.exports = Flux.Models ||
Flux.addNamespace 'Models', class Models extends Neptune.Base
  ;