# generated by Neptune Namespaces v3.x.x
# file: Art.CanvasPath/CanvasPathFile/namespace.coffee

module.exports = (require '../namespace').addNamespace('CanvasPathFile', class CanvasPathFile extends Neptune.PackageNamespace)
