// Generated by CoffeeScript 1.12.7
(function() {
  var isNode, nodeOnlyRequire;

  isNode = require('art-standard-lib').isNode;

  if (isNode) {
    nodeOnlyRequire = eval('require');
    global.AWS = nodeOnlyRequire('aws-sdk');
  } else {
    require('../../../Client');
  }

  if (!self.AWS) {
    throw new Error("Art.Aws: global.AWS required\n\nPlease use one of the following:\n\n  > require 'art-aws/Client'\n  > require 'art-aws/Server'");
  }

  module.exports = [
    {
      config: require('./Config').config
    }, require('./DynamoDb')
  ];

}).call(this);

//# sourceMappingURL=Aws.js.map
