# generated by Neptune Namespaces v1.x.x
# file: Art/Aws/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Aws'
.addModules
  Config:   require './Config'  
  DynamoDb: require './DynamoDb'
  S3:       require './S3'      
require './StreamlinedDynamoDbApi'