# generated by Neptune Namespaces v3.x.x
# file: tests/Art.SvgPathExtractor/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ConvertAllExamples: require './ConvertAllExamples'
  ConvertOutputTests: require './ConvertOutputTests'
  Data:               require './Data'              