# generated by Neptune Namespaces v3.x.x
# file: tests/Art.SvgPathExtractor/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.SvgPathExtractor', class SvgPathExtractor extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
