// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Mailgun/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Mailgun',
  (class Mailgun extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
