// generated by Neptune Namespaces v4.x.x
// file: Art/Flux/namespace.js

module.exports = require('../namespace').addNamespace(
  'Flux',
  (class Flux extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Core/namespace');
require('./Models/namespace');