// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Markdown/index.js

(module.exports = require('./namespace'))

.addModules({
  Lib:    require('./Lib'),
  Test:   require('./Test'),
  ToHtml: require('./ToHtml')
});