// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Markdown/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Markdown',
  (class Markdown extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
