# generated by Neptune Namespaces v1.x.x
# file: art/react/.Specializations/namespace.coffee

React = require '../namespace'
module.exports = React.Specializations ||
React.addNamespace 'Specializations', class Specializations extends Neptune.Base
  ;