# generated by Neptune Namespaces v0.5
# file: art/react/-Specializations/namespace.coffee

React = require '../namespace'
module.exports = React.Specializations ||
React.addNamespace 'Specializations', class Specializations extends Neptune.Base
  ;