# generated by Neptune Namespaces v3.x.x
# file: Art.SvgPathExtractor/Extractor/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Extractor'
.addModules
  CanvgCanvasMock:  require './CanvgCanvasMock' 
  StandardImport:   require './StandardImport'  
  SvgPath:          require './SvgPath'         
  SvgPathExtractor: require './SvgPathExtractor'
  SvgPathSet:       require './SvgPathSet'      