// generated by Neptune Namespaces v4.x.x
// file: Art.EngineDemos/Clipping/namespace.js

module.exports = require('../namespace').addNamespace(
  'Clipping',
  class Clipping extends Neptune.PackageNamespace {}
);
