// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServerFlux/Pipelines/index.js

(module.exports = require('./namespace'))

.addModules({
  DataUpdatesFilterPipeline: require('./DataUpdatesFilterPipeline'),
  FluxLog:                   require('./FluxLog'),
  SimpleStore:               require('./SimpleStore'),
  StandardImport:            require('./StandardImport')
});