# generated by Neptune Namespaces
# file: art/flux/react/index.coffee

(module.exports = require './namespace')
.addModules
  FluxComponent:     require './flux_component'
  FluxComponentBase: require './flux_component_base'
