# generated by Neptune Namespaces v0.5
# file: art/flux/react/index.coffee

module.exports = require './namespace'
.addModules
  FluxComponentBase: require './flux_component_base'
  FluxComponent:     require './flux_component'     