// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Ery/ClientServerFlux/Pipelines/namespace.js

module.exports = require('../namespace').addNamespace(
  'Pipelines',
  class Pipelines extends Neptune.PackageNamespace {}
);
