// generated by Neptune Namespaces v4.x.x
// file: Art.App/Tools/index.js

(module.exports = require('./namespace'))

.addModules({
  ArtEryReport:         require('./ArtEryReport'),
  CurrentConfig:        require('./CurrentConfig'),
  DescribeTableSchema:  require('./DescribeTableSchema'),
  DiffTableSchema:      require('./DiffTableSchema'),
  InitializePipelines:  require('./InitializePipelines'),
  JsonizeArtConfig:     require('./JsonizeArtConfig'),
  ListPipelines:        require('./ListPipelines'),
  ListTables:           require('./ListTables'),
  LoadTestData:         require('./LoadTestData'),
  Request:              require('./Request'),
  ScanTable:            require('./ScanTable'),
  ShowFields:           require('./ShowFields'),
  ShowInitializeParams: require('./ShowInitializeParams'),
  StatTable:            require('./StatTable'),
  UpdateIndexes:        require('./UpdateIndexes')
});