# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.Elasticsearch/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Elasticsearch'
.addModules
  ElasticsearchConfig: require './ElasticsearchConfig'
require './Pipelines'