// generated by Neptune Namespaces v4.x.x
// file: Art.EryExtensions.Elasticsearch/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Elasticsearch'))
.addModules({
  ElasticsearchConfig: require('./ElasticsearchConfig')
});
require('./Pipelines');