// generated by Neptune Namespaces v4.x.x
// file: Art.EryExtensions.Elasticsearch/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.EryExtensions.Elasticsearch',
  (class Elasticsearch extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Pipelines/namespace');