// generated by Neptune Namespaces v4.x.x
// file: Art.Chat/Configurations/index.js

(module.exports = require('./namespace'))

.addModules({
  Development: require('./Development'),
  Production:  require('./Production')
});