# generated by Neptune Namespaces v1.x.x
# file: Art/Flux/.DepricatedModels/Db/index.coffee

module.exports = require './namespace'
.addModules
  FluxDbModel:      require './FluxDbModel'     
  FluxDbModelBase:  require './FluxDbModelBase' 
  FluxDbQueryModel: require './FluxDbQueryModel'