# generated by Neptune Namespaces v1.x.x
# file: Art/Flux/.DepricatedModels/Db/namespace.coffee

DepricatedModels = require '../namespace'
module.exports = DepricatedModels.Db ||
DepricatedModels.addNamespace 'Db', class Db extends Neptune.Base
  ;