// generated by Neptune Namespaces v4.x.x
// file: Art.Mailgun/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.Mailgun',
  (class Mailgun extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
