# generated by Neptune Namespaces v0.3.0
# file: art/flux/core/index.coffee

(module.exports = require './namespace')
.addModules
  Entry:         require './entry'
  FluxModel:     require './flux_model'
  FluxStatus:    require './flux_status'
  FluxStore:     require './flux_store'
  ModelRegistry: require './model_registry'