# generated by Neptune Namespaces
# this file: src/art/flux/core/index.coffee

module.exports =
Core               = require './namespace'
Core.Entry         = require './entry'
Core.FluxModel     = require './flux_model'
Core.FluxStore     = require './flux_store'
Core.ModelRegistry = require './model_registry'
Core.finishLoad(
  ["Entry","FluxModel","FluxStore","ModelRegistry"]
)