# generated by Neptune Namespaces v3.x.x
# file: Art/React/_Specializations/namespace.coffee

module.exports = (require '../namespace').addNamespace('Specializations', class Specializations extends Neptune.PackageNamespace)
