// generated by Neptune Namespaces v4.x.x
// file: Art/React/_Specializations/namespace.js

module.exports = require('../namespace').addNamespace(
  'Specializations',
  class Specializations extends Neptune.PackageNamespace {}
);
