# generated by Neptune Namespaces v3.x.x
# file: Art.Atomic/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Atomic', class Atomic extends Neptune.PackageNamespace
  @version: require('../../package.json').version
