// generated by Neptune Namespaces v4.x.x
// file: Art.Atomic/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Atomic',
  (class Atomic extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
