// generated by Neptune Namespaces v4.x.x
// file: Art/Flux/.React/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./React'))
.addModules({
  FluxComponent: require('./FluxComponent')
});