// generated by Neptune Namespaces v4.x.x
// file: tests/index.js

(module.exports = require('./namespace'))

.addModules({
  ColorExtractor: require('./ColorExtractor'),
  StandardImport: require('./StandardImport')
});